// Mocks generated by Mockito 5.4.6 from annotations
// in software_project/test/features/followers_and_social_graph/presentation/providers/social_actions_provider_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:mockito/mockito.dart' as _i1;
import 'package:software_project/features/followers_and_social_graph/domain/entities/social_relation_entity.dart'
    as _i2;
import 'package:software_project/features/followers_and_social_graph/domain/entities/social_user_entity.dart'
    as _i5;
import 'package:software_project/features/followers_and_social_graph/domain/repositories/social_graph_repository.dart'
    as _i3;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeSocialRelationEntity_0 extends _i1.SmartFake
    implements _i2.SocialRelationEntity {
  _FakeSocialRelationEntity_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [SocialGraphRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockSocialGraphRepository extends _i1.Mock
    implements _i3.SocialGraphRepository {
  @override
  _i4.Future<List<_i5.SocialUserEntity>> getFollowers({
    required String? userId,
    int? page = 1,
    int? limit = 20,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#getFollowers, [], {
              #userId: userId,
              #page: page,
              #limit: limit,
            }),
            returnValue: _i4.Future<List<_i5.SocialUserEntity>>.value(
              <_i5.SocialUserEntity>[],
            ),
            returnValueForMissingStub:
                _i4.Future<List<_i5.SocialUserEntity>>.value(
                  <_i5.SocialUserEntity>[],
                ),
          )
          as _i4.Future<List<_i5.SocialUserEntity>>);

  @override
  _i4.Future<List<_i5.SocialUserEntity>> getFollowing({
    required String? userId,
    int? page = 1,
    int? limit = 20,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#getFollowing, [], {
              #userId: userId,
              #page: page,
              #limit: limit,
            }),
            returnValue: _i4.Future<List<_i5.SocialUserEntity>>.value(
              <_i5.SocialUserEntity>[],
            ),
            returnValueForMissingStub:
                _i4.Future<List<_i5.SocialUserEntity>>.value(
                  <_i5.SocialUserEntity>[],
                ),
          )
          as _i4.Future<List<_i5.SocialUserEntity>>);

  @override
  _i4.Future<void> followUser(String? userId) =>
      (super.noSuchMethod(
            Invocation.method(#followUser, [userId]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<void> unfollowUser(String? userId) =>
      (super.noSuchMethod(
            Invocation.method(#unfollowUser, [userId]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<void> blockUser(String? userId) =>
      (super.noSuchMethod(
            Invocation.method(#blockUser, [userId]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<void> unblockUser(String? userId) =>
      (super.noSuchMethod(
            Invocation.method(#unblockUser, [userId]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<List<_i5.SocialUserEntity>> getBlockedUsers({
    int? page = 1,
    int? limit = 20,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#getBlockedUsers, [], {
              #page: page,
              #limit: limit,
            }),
            returnValue: _i4.Future<List<_i5.SocialUserEntity>>.value(
              <_i5.SocialUserEntity>[],
            ),
            returnValueForMissingStub:
                _i4.Future<List<_i5.SocialUserEntity>>.value(
                  <_i5.SocialUserEntity>[],
                ),
          )
          as _i4.Future<List<_i5.SocialUserEntity>>);

  @override
  _i4.Future<List<_i5.SocialUserEntity>> getSuggestedUsers({
    int? page = 1,
    int? limit = 20,
    String? genre,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#getSuggestedUsers, [], {
              #page: page,
              #limit: limit,
              #genre: genre,
            }),
            returnValue: _i4.Future<List<_i5.SocialUserEntity>>.value(
              <_i5.SocialUserEntity>[],
            ),
            returnValueForMissingStub:
                _i4.Future<List<_i5.SocialUserEntity>>.value(
                  <_i5.SocialUserEntity>[],
                ),
          )
          as _i4.Future<List<_i5.SocialUserEntity>>);

  @override
  _i4.Future<_i2.SocialRelationEntity> getFollowStatus(String? userId) =>
      (super.noSuchMethod(
            Invocation.method(#getFollowStatus, [userId]),
            returnValue: _i4.Future<_i2.SocialRelationEntity>.value(
              _FakeSocialRelationEntity_0(
                this,
                Invocation.method(#getFollowStatus, [userId]),
              ),
            ),
            returnValueForMissingStub:
                _i4.Future<_i2.SocialRelationEntity>.value(
                  _FakeSocialRelationEntity_0(
                    this,
                    Invocation.method(#getFollowStatus, [userId]),
                  ),
                ),
          )
          as _i4.Future<_i2.SocialRelationEntity>);

  @override
  _i4.Future<List<_i5.SocialUserEntity>> getMutualFriends({
    required String? userId,
    int? page = 1,
    int? limit = 20,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#getMutualFriends, [], {
              #userId: userId,
              #page: page,
              #limit: limit,
            }),
            returnValue: _i4.Future<List<_i5.SocialUserEntity>>.value(
              <_i5.SocialUserEntity>[],
            ),
            returnValueForMissingStub:
                _i4.Future<List<_i5.SocialUserEntity>>.value(
                  <_i5.SocialUserEntity>[],
                ),
          )
          as _i4.Future<List<_i5.SocialUserEntity>>);
}
