// Mocks generated by Mockito 5.4.6 from annotations
// in software_project/test/features/feed_search_discovery/data/repository/discovery_repository_impl_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i12;

import 'package:dio/dio.dart' as _i2;
import 'package:mockito/mockito.dart' as _i1;
import 'package:software_project/features/feed_search_discovery/data/api/discovery_api.dart'
    as _i11;
import 'package:software_project/features/feed_search_discovery/data/dto/collection_search_response_dto.dart'
    as _i9;
import 'package:software_project/features/feed_search_discovery/data/dto/discovery_item_dto.dart'
    as _i4;
import 'package:software_project/features/feed_search_discovery/data/dto/feed_item_dto.dart'
    as _i3;
import 'package:software_project/features/feed_search_discovery/data/dto/search_result_item_dto.dart'
    as _i7;
import 'package:software_project/features/feed_search_discovery/data/dto/suggested_artist_dto.dart'
    as _i6;
import 'package:software_project/features/feed_search_discovery/data/dto/track_search_response_dto.dart'
    as _i8;
import 'package:software_project/features/feed_search_discovery/data/dto/trending_item_dto.dart'
    as _i5;
import 'package:software_project/features/feed_search_discovery/data/dto/user_search_response_dto.dart'
    as _i10;
import 'package:software_project/features/feed_search_discovery/domain/entities/collection_type.dart'
    as _i13;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeDio_0 extends _i1.SmartFake implements _i2.Dio {
  _FakeDio_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakePaginatedFeedResponseDto_1 extends _i1.SmartFake
    implements _i3.PaginatedFeedResponseDto {
  _FakePaginatedFeedResponseDto_1(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakePaginatedDiscoveryResponseDto_2 extends _i1.SmartFake
    implements _i4.PaginatedDiscoveryResponseDto {
  _FakePaginatedDiscoveryResponseDto_2(
    Object parent,
    Invocation parentInvocation,
  ) : super(parent, parentInvocation);
}

class _FakePaginatedTrendingResponseDto_3 extends _i1.SmartFake
    implements _i5.PaginatedTrendingResponseDto {
  _FakePaginatedTrendingResponseDto_3(
    Object parent,
    Invocation parentInvocation,
  ) : super(parent, parentInvocation);
}

class _FakePaginatedSuggestedArtistsResponseDto_4 extends _i1.SmartFake
    implements _i6.PaginatedSuggestedArtistsResponseDto {
  _FakePaginatedSuggestedArtistsResponseDto_4(
    Object parent,
    Invocation parentInvocation,
  ) : super(parent, parentInvocation);
}

class _FakePaginatedSearchResponseDto_5 extends _i1.SmartFake
    implements _i7.PaginatedSearchResponseDto {
  _FakePaginatedSearchResponseDto_5(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeTrackSearchResponseDto_6 extends _i1.SmartFake
    implements _i8.TrackSearchResponseDto {
  _FakeTrackSearchResponseDto_6(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeCollectionSearchResponseDto_7 extends _i1.SmartFake
    implements _i9.CollectionSearchResponseDto {
  _FakeCollectionSearchResponseDto_7(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeUserSearchResponseDto_8 extends _i1.SmartFake
    implements _i10.UserSearchResponseDto {
  _FakeUserSearchResponseDto_8(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [DiscoveryApi].
///
/// See the documentation for Mockito's code generation for more information.
class MockDiscoveryApi extends _i1.Mock implements _i11.DiscoveryApi {
  @override
  _i2.Dio get dio =>
      (super.noSuchMethod(
            Invocation.getter(#dio),
            returnValue: _FakeDio_0(this, Invocation.getter(#dio)),
            returnValueForMissingStub: _FakeDio_0(
              this,
              Invocation.getter(#dio),
            ),
          )
          as _i2.Dio);

  @override
  _i12.Future<_i3.PaginatedFeedResponseDto> getFollowingFeed({
    int? page = 1,
    int? limit = 20,
    bool? includeReposts = true,
    String? sinceTimestamp,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#getFollowingFeed, [], {
              #page: page,
              #limit: limit,
              #includeReposts: includeReposts,
              #sinceTimestamp: sinceTimestamp,
            }),
            returnValue: _i12.Future<_i3.PaginatedFeedResponseDto>.value(
              _FakePaginatedFeedResponseDto_1(
                this,
                Invocation.method(#getFollowingFeed, [], {
                  #page: page,
                  #limit: limit,
                  #includeReposts: includeReposts,
                  #sinceTimestamp: sinceTimestamp,
                }),
              ),
            ),
            returnValueForMissingStub:
                _i12.Future<_i3.PaginatedFeedResponseDto>.value(
                  _FakePaginatedFeedResponseDto_1(
                    this,
                    Invocation.method(#getFollowingFeed, [], {
                      #page: page,
                      #limit: limit,
                      #includeReposts: includeReposts,
                      #sinceTimestamp: sinceTimestamp,
                    }),
                  ),
                ),
          )
          as _i12.Future<_i3.PaginatedFeedResponseDto>);

  @override
  _i12.Future<_i4.PaginatedDiscoveryResponseDto> getDiscover({
    int? page = 1,
    int? limit = 20,
    String? genreId,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#getDiscover, [], {
              #page: page,
              #limit: limit,
              #genreId: genreId,
            }),
            returnValue: _i12.Future<_i4.PaginatedDiscoveryResponseDto>.value(
              _FakePaginatedDiscoveryResponseDto_2(
                this,
                Invocation.method(#getDiscover, [], {
                  #page: page,
                  #limit: limit,
                  #genreId: genreId,
                }),
              ),
            ),
            returnValueForMissingStub:
                _i12.Future<_i4.PaginatedDiscoveryResponseDto>.value(
                  _FakePaginatedDiscoveryResponseDto_2(
                    this,
                    Invocation.method(#getDiscover, [], {
                      #page: page,
                      #limit: limit,
                      #genreId: genreId,
                    }),
                  ),
                ),
          )
          as _i12.Future<_i4.PaginatedDiscoveryResponseDto>);

  @override
  _i12.Future<_i5.PaginatedTrendingResponseDto> getTrending({
    int? page = 1,
    int? limit = 20,
    String? type = 'track',
    String? period = 'week',
    String? genreId,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#getTrending, [], {
              #page: page,
              #limit: limit,
              #type: type,
              #period: period,
              #genreId: genreId,
            }),
            returnValue: _i12.Future<_i5.PaginatedTrendingResponseDto>.value(
              _FakePaginatedTrendingResponseDto_3(
                this,
                Invocation.method(#getTrending, [], {
                  #page: page,
                  #limit: limit,
                  #type: type,
                  #period: period,
                  #genreId: genreId,
                }),
              ),
            ),
            returnValueForMissingStub:
                _i12.Future<_i5.PaginatedTrendingResponseDto>.value(
                  _FakePaginatedTrendingResponseDto_3(
                    this,
                    Invocation.method(#getTrending, [], {
                      #page: page,
                      #limit: limit,
                      #type: type,
                      #period: period,
                      #genreId: genreId,
                    }),
                  ),
                ),
          )
          as _i12.Future<_i5.PaginatedTrendingResponseDto>);

  @override
  _i12.Future<_i6.PaginatedSuggestedArtistsResponseDto> getSuggestedArtists({
    int? page = 1,
    int? limit = 10,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#getSuggestedArtists, [], {
              #page: page,
              #limit: limit,
            }),
            returnValue:
                _i12.Future<_i6.PaginatedSuggestedArtistsResponseDto>.value(
                  _FakePaginatedSuggestedArtistsResponseDto_4(
                    this,
                    Invocation.method(#getSuggestedArtists, [], {
                      #page: page,
                      #limit: limit,
                    }),
                  ),
                ),
            returnValueForMissingStub:
                _i12.Future<_i6.PaginatedSuggestedArtistsResponseDto>.value(
                  _FakePaginatedSuggestedArtistsResponseDto_4(
                    this,
                    Invocation.method(#getSuggestedArtists, [], {
                      #page: page,
                      #limit: limit,
                    }),
                  ),
                ),
          )
          as _i12.Future<_i6.PaginatedSuggestedArtistsResponseDto>);

  @override
  _i12.Future<_i7.PaginatedSearchResponseDto> search({
    required String? q,
    int? page = 1,
    int? limit = 20,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#search, [], {#q: q, #page: page, #limit: limit}),
            returnValue: _i12.Future<_i7.PaginatedSearchResponseDto>.value(
              _FakePaginatedSearchResponseDto_5(
                this,
                Invocation.method(#search, [], {
                  #q: q,
                  #page: page,
                  #limit: limit,
                }),
              ),
            ),
            returnValueForMissingStub:
                _i12.Future<_i7.PaginatedSearchResponseDto>.value(
                  _FakePaginatedSearchResponseDto_5(
                    this,
                    Invocation.method(#search, [], {
                      #q: q,
                      #page: page,
                      #limit: limit,
                    }),
                  ),
                ),
          )
          as _i12.Future<_i7.PaginatedSearchResponseDto>);

  @override
  _i12.Future<_i8.TrackSearchResponseDto> searchTracks({
    required String? q,
    int? page = 1,
    int? limit = 20,
    String? tag,
    String? timeAdded,
    String? duration,
    String? toListen,
    bool? allowDownloads,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#searchTracks, [], {
              #q: q,
              #page: page,
              #limit: limit,
              #tag: tag,
              #timeAdded: timeAdded,
              #duration: duration,
              #toListen: toListen,
              #allowDownloads: allowDownloads,
            }),
            returnValue: _i12.Future<_i8.TrackSearchResponseDto>.value(
              _FakeTrackSearchResponseDto_6(
                this,
                Invocation.method(#searchTracks, [], {
                  #q: q,
                  #page: page,
                  #limit: limit,
                  #tag: tag,
                  #timeAdded: timeAdded,
                  #duration: duration,
                  #toListen: toListen,
                  #allowDownloads: allowDownloads,
                }),
              ),
            ),
            returnValueForMissingStub:
                _i12.Future<_i8.TrackSearchResponseDto>.value(
                  _FakeTrackSearchResponseDto_6(
                    this,
                    Invocation.method(#searchTracks, [], {
                      #q: q,
                      #page: page,
                      #limit: limit,
                      #tag: tag,
                      #timeAdded: timeAdded,
                      #duration: duration,
                      #toListen: toListen,
                      #allowDownloads: allowDownloads,
                    }),
                  ),
                ),
          )
          as _i12.Future<_i8.TrackSearchResponseDto>);

  @override
  _i12.Future<_i9.CollectionSearchResponseDto> searchCollections({
    required String? q,
    int? page = 1,
    int? limit = 20,
    _i13.CollectionType? type,
    String? tag,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#searchCollections, [], {
              #q: q,
              #page: page,
              #limit: limit,
              #type: type,
              #tag: tag,
            }),
            returnValue: _i12.Future<_i9.CollectionSearchResponseDto>.value(
              _FakeCollectionSearchResponseDto_7(
                this,
                Invocation.method(#searchCollections, [], {
                  #q: q,
                  #page: page,
                  #limit: limit,
                  #type: type,
                  #tag: tag,
                }),
              ),
            ),
            returnValueForMissingStub:
                _i12.Future<_i9.CollectionSearchResponseDto>.value(
                  _FakeCollectionSearchResponseDto_7(
                    this,
                    Invocation.method(#searchCollections, [], {
                      #q: q,
                      #page: page,
                      #limit: limit,
                      #type: type,
                      #tag: tag,
                    }),
                  ),
                ),
          )
          as _i12.Future<_i9.CollectionSearchResponseDto>);

  @override
  _i12.Future<_i10.UserSearchResponseDto> searchPeople({
    required String? q,
    int? page = 1,
    int? limit = 20,
    String? location,
    int? minFollowers,
    bool? verifiedOnly,
    String? sort = 'relevance',
  }) =>
      (super.noSuchMethod(
            Invocation.method(#searchPeople, [], {
              #q: q,
              #page: page,
              #limit: limit,
              #location: location,
              #minFollowers: minFollowers,
              #verifiedOnly: verifiedOnly,
              #sort: sort,
            }),
            returnValue: _i12.Future<_i10.UserSearchResponseDto>.value(
              _FakeUserSearchResponseDto_8(
                this,
                Invocation.method(#searchPeople, [], {
                  #q: q,
                  #page: page,
                  #limit: limit,
                  #location: location,
                  #minFollowers: minFollowers,
                  #verifiedOnly: verifiedOnly,
                  #sort: sort,
                }),
              ),
            ),
            returnValueForMissingStub:
                _i12.Future<_i10.UserSearchResponseDto>.value(
                  _FakeUserSearchResponseDto_8(
                    this,
                    Invocation.method(#searchPeople, [], {
                      #q: q,
                      #page: page,
                      #limit: limit,
                      #location: location,
                      #minFollowers: minFollowers,
                      #verifiedOnly: verifiedOnly,
                      #sort: sort,
                    }),
                  ),
                ),
          )
          as _i12.Future<_i10.UserSearchResponseDto>);
}
