// Mocks generated by Mockito 5.4.6 from annotations
// in software_project/test/features/feed_search_discovery/data/repository/mock_repository_impls_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i6;

import 'package:mockito/mockito.dart' as _i1;
import 'package:software_project/features/feed_search_discovery/data/services/mock_feed_service.dart'
    as _i5;
import 'package:software_project/features/feed_search_discovery/data/services/mock_search_service.dart'
    as _i8;
import 'package:software_project/features/feed_search_discovery/data/services/mock_trending_service.dart'
    as _i14;
import 'package:software_project/features/feed_search_discovery/domain/entities/album_result_entity.dart'
    as _i13;
import 'package:software_project/features/feed_search_discovery/domain/entities/feed_item_entity.dart'
    as _i7;
import 'package:software_project/features/feed_search_discovery/domain/entities/genre_detail_entity.dart'
    as _i3;
import 'package:software_project/features/feed_search_discovery/domain/entities/playlist_result_entity.dart'
    as _i12;
import 'package:software_project/features/feed_search_discovery/domain/entities/profile_result_entity.dart'
    as _i11;
import 'package:software_project/features/feed_search_discovery/domain/entities/search_all_result_entity.dart'
    as _i2;
import 'package:software_project/features/feed_search_discovery/domain/entities/search_genre_entity.dart'
    as _i9;
import 'package:software_project/features/feed_search_discovery/domain/entities/track_result_entity.dart'
    as _i10;
import 'package:software_project/features/feed_search_discovery/domain/entities/trending_genre_entity.dart'
    as _i4;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeSearchAllResultEntity_0 extends _i1.SmartFake
    implements _i2.SearchAllResultEntity {
  _FakeSearchAllResultEntity_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeGenreDetailEntity_1 extends _i1.SmartFake
    implements _i3.GenreDetailEntity {
  _FakeGenreDetailEntity_1(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeTrendingGenreEntity_2 extends _i1.SmartFake
    implements _i4.TrendingGenreEntity {
  _FakeTrendingGenreEntity_2(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [MockFeedService].
///
/// See the documentation for Mockito's code generation for more information.
class MockMockFeedService extends _i1.Mock implements _i5.MockFeedService {
  @override
  _i6.Future<List<_i7.FeedItemEntity>> getFollowingFeed() =>
      (super.noSuchMethod(
            Invocation.method(#getFollowingFeed, []),
            returnValue: _i6.Future<List<_i7.FeedItemEntity>>.value(
              <_i7.FeedItemEntity>[],
            ),
            returnValueForMissingStub:
                _i6.Future<List<_i7.FeedItemEntity>>.value(
                  <_i7.FeedItemEntity>[],
                ),
          )
          as _i6.Future<List<_i7.FeedItemEntity>>);

  @override
  _i6.Future<List<_i7.FeedItemEntity>> getDiscoverFeed() =>
      (super.noSuchMethod(
            Invocation.method(#getDiscoverFeed, []),
            returnValue: _i6.Future<List<_i7.FeedItemEntity>>.value(
              <_i7.FeedItemEntity>[],
            ),
            returnValueForMissingStub:
                _i6.Future<List<_i7.FeedItemEntity>>.value(
                  <_i7.FeedItemEntity>[],
                ),
          )
          as _i6.Future<List<_i7.FeedItemEntity>>);
}

/// A class which mocks [MockSearchService].
///
/// See the documentation for Mockito's code generation for more information.
class MockMockSearchService extends _i1.Mock implements _i8.MockSearchService {
  @override
  _i6.Future<List<_i9.SearchGenreEntity>> getGenres() =>
      (super.noSuchMethod(
            Invocation.method(#getGenres, []),
            returnValue: _i6.Future<List<_i9.SearchGenreEntity>>.value(
              <_i9.SearchGenreEntity>[],
            ),
            returnValueForMissingStub:
                _i6.Future<List<_i9.SearchGenreEntity>>.value(
                  <_i9.SearchGenreEntity>[],
                ),
          )
          as _i6.Future<List<_i9.SearchGenreEntity>>);

  @override
  _i6.Future<_i2.SearchAllResultEntity> searchAll(String? query) =>
      (super.noSuchMethod(
            Invocation.method(#searchAll, [query]),
            returnValue: _i6.Future<_i2.SearchAllResultEntity>.value(
              _FakeSearchAllResultEntity_0(
                this,
                Invocation.method(#searchAll, [query]),
              ),
            ),
            returnValueForMissingStub:
                _i6.Future<_i2.SearchAllResultEntity>.value(
                  _FakeSearchAllResultEntity_0(
                    this,
                    Invocation.method(#searchAll, [query]),
                  ),
                ),
          )
          as _i6.Future<_i2.SearchAllResultEntity>);

  @override
  _i6.Future<List<_i10.TrackResultEntity>> searchTracks(
    String? query, {
    int? page = 1,
    int? limit = 20,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #searchTracks,
              [query],
              {#page: page, #limit: limit},
            ),
            returnValue: _i6.Future<List<_i10.TrackResultEntity>>.value(
              <_i10.TrackResultEntity>[],
            ),
            returnValueForMissingStub:
                _i6.Future<List<_i10.TrackResultEntity>>.value(
                  <_i10.TrackResultEntity>[],
                ),
          )
          as _i6.Future<List<_i10.TrackResultEntity>>);

  @override
  _i6.Future<List<_i11.ProfileResultEntity>> searchProfiles(
    String? query, {
    int? page = 1,
    int? limit = 20,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #searchProfiles,
              [query],
              {#page: page, #limit: limit},
            ),
            returnValue: _i6.Future<List<_i11.ProfileResultEntity>>.value(
              <_i11.ProfileResultEntity>[],
            ),
            returnValueForMissingStub:
                _i6.Future<List<_i11.ProfileResultEntity>>.value(
                  <_i11.ProfileResultEntity>[],
                ),
          )
          as _i6.Future<List<_i11.ProfileResultEntity>>);

  @override
  _i6.Future<List<_i12.PlaylistResultEntity>> searchPlaylists(
    String? query, {
    int? page = 1,
    int? limit = 20,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #searchPlaylists,
              [query],
              {#page: page, #limit: limit},
            ),
            returnValue: _i6.Future<List<_i12.PlaylistResultEntity>>.value(
              <_i12.PlaylistResultEntity>[],
            ),
            returnValueForMissingStub:
                _i6.Future<List<_i12.PlaylistResultEntity>>.value(
                  <_i12.PlaylistResultEntity>[],
                ),
          )
          as _i6.Future<List<_i12.PlaylistResultEntity>>);

  @override
  _i6.Future<List<_i13.AlbumResultEntity>> searchAlbums(
    String? query, {
    int? page = 1,
    int? limit = 20,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #searchAlbums,
              [query],
              {#page: page, #limit: limit},
            ),
            returnValue: _i6.Future<List<_i13.AlbumResultEntity>>.value(
              <_i13.AlbumResultEntity>[],
            ),
            returnValueForMissingStub:
                _i6.Future<List<_i13.AlbumResultEntity>>.value(
                  <_i13.AlbumResultEntity>[],
                ),
          )
          as _i6.Future<List<_i13.AlbumResultEntity>>);

  @override
  _i6.Future<_i3.GenreDetailEntity> getGenreDetail(String? genreId) =>
      (super.noSuchMethod(
            Invocation.method(#getGenreDetail, [genreId]),
            returnValue: _i6.Future<_i3.GenreDetailEntity>.value(
              _FakeGenreDetailEntity_1(
                this,
                Invocation.method(#getGenreDetail, [genreId]),
              ),
            ),
            returnValueForMissingStub: _i6.Future<_i3.GenreDetailEntity>.value(
              _FakeGenreDetailEntity_1(
                this,
                Invocation.method(#getGenreDetail, [genreId]),
              ),
            ),
          )
          as _i6.Future<_i3.GenreDetailEntity>);
}

/// A class which mocks [MockTrendingService].
///
/// See the documentation for Mockito's code generation for more information.
class MockMockTrendingService extends _i1.Mock
    implements _i14.MockTrendingService {
  @override
  _i6.Future<_i4.TrendingGenreEntity> getTrendingByGenre({
    required String? genre,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#getTrendingByGenre, [], {#genre: genre}),
            returnValue: _i6.Future<_i4.TrendingGenreEntity>.value(
              _FakeTrendingGenreEntity_2(
                this,
                Invocation.method(#getTrendingByGenre, [], {#genre: genre}),
              ),
            ),
            returnValueForMissingStub:
                _i6.Future<_i4.TrendingGenreEntity>.value(
                  _FakeTrendingGenreEntity_2(
                    this,
                    Invocation.method(#getTrendingByGenre, [], {#genre: genre}),
                  ),
                ),
          )
          as _i6.Future<_i4.TrendingGenreEntity>);
}
