// Mocks generated by Mockito 5.4.6 from annotations
// in software_project/test/features/feed_search_discovery/presentation/providers/trending_notifier_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:mockito/mockito.dart' as _i1;
import 'package:software_project/features/feed_search_discovery/domain/entities/trending_genre_entity.dart'
    as _i2;
import 'package:software_project/features/feed_search_discovery/domain/repositories/trending_repository.dart'
    as _i3;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeTrendingGenreEntity_0 extends _i1.SmartFake
    implements _i2.TrendingGenreEntity {
  _FakeTrendingGenreEntity_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [TrendingRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockTrendingRepository extends _i1.Mock
    implements _i3.TrendingRepository {
  @override
  _i4.Future<_i2.TrendingGenreEntity> getTrending({required String? genre}) =>
      (super.noSuchMethod(
            Invocation.method(#getTrending, [], {#genre: genre}),
            returnValue: _i4.Future<_i2.TrendingGenreEntity>.value(
              _FakeTrendingGenreEntity_0(
                this,
                Invocation.method(#getTrending, [], {#genre: genre}),
              ),
            ),
            returnValueForMissingStub:
                _i4.Future<_i2.TrendingGenreEntity>.value(
                  _FakeTrendingGenreEntity_0(
                    this,
                    Invocation.method(#getTrending, [], {#genre: genre}),
                  ),
                ),
          )
          as _i4.Future<_i2.TrendingGenreEntity>);
}
