// Mocks generated by Mockito 5.4.6 from annotations
// in software_project/test/helpers/mocks.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i5;

import 'package:dio/dio.dart' as _i3;
import 'package:mockito/mockito.dart' as _i1;
import 'package:software_project/core/storage/token_storage.dart' as _i11;
import 'package:software_project/features/auth/data/api/auth_api.dart' as _i6;
import 'package:software_project/features/auth/data/dto/check_email_request_dto.dart'
    as _i7;
import 'package:software_project/features/auth/data/dto/login_request_dto.dart'
    as _i10;
import 'package:software_project/features/auth/data/dto/register_request_dto.dart'
    as _i8;
import 'package:software_project/features/auth/data/dto/verify_email_request_dto.dart'
    as _i9;
import 'package:software_project/features/auth/data/services/google_sign_in_service.dart'
    as _i22;
import 'package:software_project/features/auth/domain/entities/auth_user_entity.dart'
    as _i2;
import 'package:software_project/features/auth/domain/repositories/auth_repository.dart'
    as _i4;
import 'package:software_project/features/auth/domain/usecases/check_email_usecase.dart'
    as _i12;
import 'package:software_project/features/auth/domain/usecases/delete_account_usecase.dart'
    as _i21;
import 'package:software_project/features/auth/domain/usecases/forgot_password_usecase.dart'
    as _i19;
import 'package:software_project/features/auth/domain/usecases/login_usecase.dart'
    as _i16;
import 'package:software_project/features/auth/domain/usecases/logout_all_usecase.dart'
    as _i18;
import 'package:software_project/features/auth/domain/usecases/logout_usecase.dart'
    as _i17;
import 'package:software_project/features/auth/domain/usecases/register_usecase.dart'
    as _i13;
import 'package:software_project/features/auth/domain/usecases/resend_verification_usecase.dart'
    as _i15;
import 'package:software_project/features/auth/domain/usecases/reset_password_usecase.dart'
    as _i20;
import 'package:software_project/features/auth/domain/usecases/verify_email_usecase.dart'
    as _i14;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeAuthUserEntity_0 extends _i1.SmartFake
    implements _i2.AuthUserEntity {
  _FakeAuthUserEntity_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeResponse_1<T> extends _i1.SmartFake implements _i3.Response<T> {
  _FakeResponse_1(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [AuthRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockAuthRepository extends _i1.Mock implements _i4.AuthRepository {
  MockAuthRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i5.Future<bool> checkEmail(String? email) =>
      (super.noSuchMethod(
            Invocation.method(#checkEmail, [email]),
            returnValue: _i5.Future<bool>.value(false),
          )
          as _i5.Future<bool>);

  @override
  _i5.Future<void> register({
    required String? email,
    required String? username,
    required String? password,
    required String? gender,
    required String? dateOfBirth,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#register, [], {
              #email: email,
              #username: username,
              #password: password,
              #gender: gender,
              #dateOfBirth: dateOfBirth,
            }),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<_i2.AuthUserEntity> verifyEmail(String? email, String? token) =>
      (super.noSuchMethod(
            Invocation.method(#verifyEmail, [email, token]),
            returnValue: _i5.Future<_i2.AuthUserEntity>.value(
              _FakeAuthUserEntity_0(
                this,
                Invocation.method(#verifyEmail, [email, token]),
              ),
            ),
          )
          as _i5.Future<_i2.AuthUserEntity>);

  @override
  _i5.Future<void> resendVerification(String? email) =>
      (super.noSuchMethod(
            Invocation.method(#resendVerification, [email]),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<_i2.AuthUserEntity> login(String? email, String? password) =>
      (super.noSuchMethod(
            Invocation.method(#login, [email, password]),
            returnValue: _i5.Future<_i2.AuthUserEntity>.value(
              _FakeAuthUserEntity_0(
                this,
                Invocation.method(#login, [email, password]),
              ),
            ),
          )
          as _i5.Future<_i2.AuthUserEntity>);

  @override
  _i5.Future<_i2.AuthUserEntity> oauthGoogleSignIn({
    required String? authorizationCode,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#oauthGoogleSignIn, [], {
              #authorizationCode: authorizationCode,
            }),
            returnValue: _i5.Future<_i2.AuthUserEntity>.value(
              _FakeAuthUserEntity_0(
                this,
                Invocation.method(#oauthGoogleSignIn, [], {
                  #authorizationCode: authorizationCode,
                }),
              ),
            ),
          )
          as _i5.Future<_i2.AuthUserEntity>);

  @override
  _i5.Future<_i2.AuthUserEntity> linkGoogleAccount({
    required String? linkingToken,
    required String? password,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#linkGoogleAccount, [], {
              #linkingToken: linkingToken,
              #password: password,
            }),
            returnValue: _i5.Future<_i2.AuthUserEntity>.value(
              _FakeAuthUserEntity_0(
                this,
                Invocation.method(#linkGoogleAccount, [], {
                  #linkingToken: linkingToken,
                  #password: password,
                }),
              ),
            ),
          )
          as _i5.Future<_i2.AuthUserEntity>);

  @override
  _i5.Future<void> signOut() =>
      (super.noSuchMethod(
            Invocation.method(#signOut, []),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<void> signOutAll() =>
      (super.noSuchMethod(
            Invocation.method(#signOutAll, []),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<void> forgotPassword(String? email) =>
      (super.noSuchMethod(
            Invocation.method(#forgotPassword, [email]),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<void> resetPassword({
    required String? email,
    required String? token,
    required String? newPassword,
    required String? confirmPassword,
    bool? signoutAll = true,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#resetPassword, [], {
              #email: email,
              #token: token,
              #newPassword: newPassword,
              #confirmPassword: confirmPassword,
              #signoutAll: signoutAll,
            }),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<void> deleteAccount({String? password}) =>
      (super.noSuchMethod(
            Invocation.method(#deleteAccount, [], {#password: password}),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);
}

/// A class which mocks [AuthApi].
///
/// See the documentation for Mockito's code generation for more information.
class MockAuthApi extends _i1.Mock implements _i6.AuthApi {
  MockAuthApi() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i5.Future<_i3.Response<dynamic>> checkEmail(_i7.CheckEmailRequestDto? dto) =>
      (super.noSuchMethod(
            Invocation.method(#checkEmail, [dto]),
            returnValue: _i5.Future<_i3.Response<dynamic>>.value(
              _FakeResponse_1<dynamic>(
                this,
                Invocation.method(#checkEmail, [dto]),
              ),
            ),
          )
          as _i5.Future<_i3.Response<dynamic>>);

  @override
  _i5.Future<_i3.Response<dynamic>> register(_i8.RegisterRequestDto? dto) =>
      (super.noSuchMethod(
            Invocation.method(#register, [dto]),
            returnValue: _i5.Future<_i3.Response<dynamic>>.value(
              _FakeResponse_1<dynamic>(
                this,
                Invocation.method(#register, [dto]),
              ),
            ),
          )
          as _i5.Future<_i3.Response<dynamic>>);

  @override
  _i5.Future<_i3.Response<dynamic>> verifyEmail(
    _i9.VerifyEmailRequestDto? dto,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#verifyEmail, [dto]),
            returnValue: _i5.Future<_i3.Response<dynamic>>.value(
              _FakeResponse_1<dynamic>(
                this,
                Invocation.method(#verifyEmail, [dto]),
              ),
            ),
          )
          as _i5.Future<_i3.Response<dynamic>>);

  @override
  _i5.Future<_i3.Response<dynamic>> resendVerification(String? email) =>
      (super.noSuchMethod(
            Invocation.method(#resendVerification, [email]),
            returnValue: _i5.Future<_i3.Response<dynamic>>.value(
              _FakeResponse_1<dynamic>(
                this,
                Invocation.method(#resendVerification, [email]),
              ),
            ),
          )
          as _i5.Future<_i3.Response<dynamic>>);

  @override
  _i5.Future<_i3.Response<dynamic>> login(_i10.LoginRequestDto? dto) =>
      (super.noSuchMethod(
            Invocation.method(#login, [dto]),
            returnValue: _i5.Future<_i3.Response<dynamic>>.value(
              _FakeResponse_1<dynamic>(this, Invocation.method(#login, [dto])),
            ),
          )
          as _i5.Future<_i3.Response<dynamic>>);

  @override
  _i5.Future<_i3.Response<dynamic>> oauthGoogle({required String? code}) =>
      (super.noSuchMethod(
            Invocation.method(#oauthGoogle, [], {#code: code}),
            returnValue: _i5.Future<_i3.Response<dynamic>>.value(
              _FakeResponse_1<dynamic>(
                this,
                Invocation.method(#oauthGoogle, [], {#code: code}),
              ),
            ),
          )
          as _i5.Future<_i3.Response<dynamic>>);

  @override
  _i5.Future<_i3.Response<dynamic>> oauthGoogleLink({
    required String? linkingToken,
    required String? password,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#oauthGoogleLink, [], {
              #linkingToken: linkingToken,
              #password: password,
            }),
            returnValue: _i5.Future<_i3.Response<dynamic>>.value(
              _FakeResponse_1<dynamic>(
                this,
                Invocation.method(#oauthGoogleLink, [], {
                  #linkingToken: linkingToken,
                  #password: password,
                }),
              ),
            ),
          )
          as _i5.Future<_i3.Response<dynamic>>);

  @override
  _i5.Future<_i3.Response<dynamic>> signOut(String? refreshToken) =>
      (super.noSuchMethod(
            Invocation.method(#signOut, [refreshToken]),
            returnValue: _i5.Future<_i3.Response<dynamic>>.value(
              _FakeResponse_1<dynamic>(
                this,
                Invocation.method(#signOut, [refreshToken]),
              ),
            ),
          )
          as _i5.Future<_i3.Response<dynamic>>);

  @override
  _i5.Future<_i3.Response<dynamic>> signOutAll(String? refreshToken) =>
      (super.noSuchMethod(
            Invocation.method(#signOutAll, [refreshToken]),
            returnValue: _i5.Future<_i3.Response<dynamic>>.value(
              _FakeResponse_1<dynamic>(
                this,
                Invocation.method(#signOutAll, [refreshToken]),
              ),
            ),
          )
          as _i5.Future<_i3.Response<dynamic>>);

  @override
  _i5.Future<_i3.Response<dynamic>> forgotPassword(String? email) =>
      (super.noSuchMethod(
            Invocation.method(#forgotPassword, [email]),
            returnValue: _i5.Future<_i3.Response<dynamic>>.value(
              _FakeResponse_1<dynamic>(
                this,
                Invocation.method(#forgotPassword, [email]),
              ),
            ),
          )
          as _i5.Future<_i3.Response<dynamic>>);

  @override
  _i5.Future<_i3.Response<dynamic>> resetPassword({
    required String? email,
    required String? token,
    required String? newPassword,
    required String? confirmPassword,
    bool? signoutAll = true,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#resetPassword, [], {
              #email: email,
              #token: token,
              #newPassword: newPassword,
              #confirmPassword: confirmPassword,
              #signoutAll: signoutAll,
            }),
            returnValue: _i5.Future<_i3.Response<dynamic>>.value(
              _FakeResponse_1<dynamic>(
                this,
                Invocation.method(#resetPassword, [], {
                  #email: email,
                  #token: token,
                  #newPassword: newPassword,
                  #confirmPassword: confirmPassword,
                  #signoutAll: signoutAll,
                }),
              ),
            ),
          )
          as _i5.Future<_i3.Response<dynamic>>);

  @override
  _i5.Future<_i3.Response<dynamic>> deleteAccount({String? password}) =>
      (super.noSuchMethod(
            Invocation.method(#deleteAccount, [], {#password: password}),
            returnValue: _i5.Future<_i3.Response<dynamic>>.value(
              _FakeResponse_1<dynamic>(
                this,
                Invocation.method(#deleteAccount, [], {#password: password}),
              ),
            ),
          )
          as _i5.Future<_i3.Response<dynamic>>);
}

/// A class which mocks [TokenStorage].
///
/// See the documentation for Mockito's code generation for more information.
class MockTokenStorage extends _i1.Mock implements _i11.TokenStorage {
  MockTokenStorage() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i5.Future<void> saveTokens({
    required String? accessToken,
    required String? refreshToken,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#saveTokens, [], {
              #accessToken: accessToken,
              #refreshToken: refreshToken,
            }),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<void> saveUser(_i2.AuthUserEntity? user) =>
      (super.noSuchMethod(
            Invocation.method(#saveUser, [user]),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<void> saveSession({
    required String? accessToken,
    required String? refreshToken,
    required _i2.AuthUserEntity? user,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#saveSession, [], {
              #accessToken: accessToken,
              #refreshToken: refreshToken,
              #user: user,
            }),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<String?> getAccessToken() =>
      (super.noSuchMethod(
            Invocation.method(#getAccessToken, []),
            returnValue: _i5.Future<String?>.value(),
          )
          as _i5.Future<String?>);

  @override
  _i5.Future<String?> getRefreshToken() =>
      (super.noSuchMethod(
            Invocation.method(#getRefreshToken, []),
            returnValue: _i5.Future<String?>.value(),
          )
          as _i5.Future<String?>);

  @override
  _i5.Future<_i2.AuthUserEntity?> getUser() =>
      (super.noSuchMethod(
            Invocation.method(#getUser, []),
            returnValue: _i5.Future<_i2.AuthUserEntity?>.value(),
          )
          as _i5.Future<_i2.AuthUserEntity?>);

  @override
  _i5.Future<bool> hasAccessToken() =>
      (super.noSuchMethod(
            Invocation.method(#hasAccessToken, []),
            returnValue: _i5.Future<bool>.value(false),
          )
          as _i5.Future<bool>);

  @override
  _i5.Future<void> clearTokens() =>
      (super.noSuchMethod(
            Invocation.method(#clearTokens, []),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<void> clearUser() =>
      (super.noSuchMethod(
            Invocation.method(#clearUser, []),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<void> clearSession() =>
      (super.noSuchMethod(
            Invocation.method(#clearSession, []),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);
}

/// A class which mocks [CheckEmailUseCase].
///
/// See the documentation for Mockito's code generation for more information.
class MockCheckEmailUseCase extends _i1.Mock implements _i12.CheckEmailUseCase {
  MockCheckEmailUseCase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i5.Future<bool> call(String? email) =>
      (super.noSuchMethod(
            Invocation.method(#call, [email]),
            returnValue: _i5.Future<bool>.value(false),
          )
          as _i5.Future<bool>);
}

/// A class which mocks [RegisterUseCase].
///
/// See the documentation for Mockito's code generation for more information.
class MockRegisterUseCase extends _i1.Mock implements _i13.RegisterUseCase {
  MockRegisterUseCase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i5.Future<void> call({
    required String? email,
    required String? username,
    required String? password,
    required String? gender,
    required String? dateOfBirth,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#call, [], {
              #email: email,
              #username: username,
              #password: password,
              #gender: gender,
              #dateOfBirth: dateOfBirth,
            }),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);
}

/// A class which mocks [VerifyEmailUseCase].
///
/// See the documentation for Mockito's code generation for more information.
class MockVerifyEmailUseCase extends _i1.Mock
    implements _i14.VerifyEmailUseCase {
  MockVerifyEmailUseCase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i5.Future<_i2.AuthUserEntity> call(String? email, String? token) =>
      (super.noSuchMethod(
            Invocation.method(#call, [email, token]),
            returnValue: _i5.Future<_i2.AuthUserEntity>.value(
              _FakeAuthUserEntity_0(
                this,
                Invocation.method(#call, [email, token]),
              ),
            ),
          )
          as _i5.Future<_i2.AuthUserEntity>);
}

/// A class which mocks [ResendVerificationUseCase].
///
/// See the documentation for Mockito's code generation for more information.
class MockResendVerificationUseCase extends _i1.Mock
    implements _i15.ResendVerificationUseCase {
  MockResendVerificationUseCase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i5.Future<void> call(String? email) =>
      (super.noSuchMethod(
            Invocation.method(#call, [email]),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);
}

/// A class which mocks [LoginUseCase].
///
/// See the documentation for Mockito's code generation for more information.
class MockLoginUseCase extends _i1.Mock implements _i16.LoginUseCase {
  MockLoginUseCase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i5.Future<_i2.AuthUserEntity> call(String? email, String? password) =>
      (super.noSuchMethod(
            Invocation.method(#call, [email, password]),
            returnValue: _i5.Future<_i2.AuthUserEntity>.value(
              _FakeAuthUserEntity_0(
                this,
                Invocation.method(#call, [email, password]),
              ),
            ),
          )
          as _i5.Future<_i2.AuthUserEntity>);
}

/// A class which mocks [LogoutUseCase].
///
/// See the documentation for Mockito's code generation for more information.
class MockLogoutUseCase extends _i1.Mock implements _i17.LogoutUseCase {
  MockLogoutUseCase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i5.Future<void> call() =>
      (super.noSuchMethod(
            Invocation.method(#call, []),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);
}

/// A class which mocks [LogoutAllUseCase].
///
/// See the documentation for Mockito's code generation for more information.
class MockLogoutAllUseCase extends _i1.Mock implements _i18.LogoutAllUseCase {
  MockLogoutAllUseCase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i5.Future<void> call() =>
      (super.noSuchMethod(
            Invocation.method(#call, []),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);
}

/// A class which mocks [ForgotPasswordUseCase].
///
/// See the documentation for Mockito's code generation for more information.
class MockForgotPasswordUseCase extends _i1.Mock
    implements _i19.ForgotPasswordUseCase {
  MockForgotPasswordUseCase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i5.Future<void> call(String? email) =>
      (super.noSuchMethod(
            Invocation.method(#call, [email]),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);
}

/// A class which mocks [ResetPasswordUseCase].
///
/// See the documentation for Mockito's code generation for more information.
class MockResetPasswordUseCase extends _i1.Mock
    implements _i20.ResetPasswordUseCase {
  MockResetPasswordUseCase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i5.Future<void> call({
    required String? email,
    required String? token,
    required String? newPassword,
    required String? confirmPassword,
    bool? signoutAll = true,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#call, [], {
              #email: email,
              #token: token,
              #newPassword: newPassword,
              #confirmPassword: confirmPassword,
              #signoutAll: signoutAll,
            }),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);
}

/// A class which mocks [DeleteAccountUseCase].
///
/// See the documentation for Mockito's code generation for more information.
class MockDeleteAccountUseCase extends _i1.Mock
    implements _i21.DeleteAccountUseCase {
  MockDeleteAccountUseCase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i5.Future<void> call({String? password}) =>
      (super.noSuchMethod(
            Invocation.method(#call, [], {#password: password}),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);
}

/// A class which mocks [GoogleSignInService].
///
/// See the documentation for Mockito's code generation for more information.
class MockGoogleSignInService extends _i1.Mock
    implements _i22.GoogleSignInService {
  MockGoogleSignInService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i5.Future<_i22.GoogleSignInResult?> signIn() =>
      (super.noSuchMethod(
            Invocation.method(#signIn, []),
            returnValue: _i5.Future<_i22.GoogleSignInResult?>.value(),
          )
          as _i5.Future<_i22.GoogleSignInResult?>);

  @override
  _i5.Future<void> signOut() =>
      (super.noSuchMethod(
            Invocation.method(#signOut, []),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<void> disconnect() =>
      (super.noSuchMethod(
            Invocation.method(#disconnect, []),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);
}
