// Mocks generated by Mockito 5.4.6 from annotations
// in software_project/test/helpers/upload_mocks.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i18;

import 'package:dio/dio.dart' as _i7;
import 'package:dio/src/adapter.dart' as _i4;
import 'package:dio/src/cancel_token.dart' as _i19;
import 'package:dio/src/dio_mixin.dart' as _i3;
import 'package:dio/src/options.dart' as _i2;
import 'package:dio/src/response.dart' as _i6;
import 'package:dio/src/transformer.dart' as _i5;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i30;
import 'package:software_project/features/audio_upload_and_management/data/api/library_uploads_api.dart'
    as _i24;
import 'package:software_project/features/audio_upload_and_management/data/api/mock_library_uploads_api.dart'
    as _i25;
import 'package:software_project/features/audio_upload_and_management/data/api/upload_api.dart'
    as _i20;
import 'package:software_project/features/audio_upload_and_management/data/dto/artist_tools_quota_dto.dart'
    as _i10;
import 'package:software_project/features/audio_upload_and_management/data/dto/create_track_request_dto.dart'
    as _i21;
import 'package:software_project/features/audio_upload_and_management/data/dto/finalize_track_metadata_request_dto.dart'
    as _i23;
import 'package:software_project/features/audio_upload_and_management/data/dto/track_response_dto.dart'
    as _i9;
import 'package:software_project/features/audio_upload_and_management/data/dto/upload_item_dto.dart'
    as _i11;
import 'package:software_project/features/audio_upload_and_management/data/dto/upload_quota_dto.dart'
    as _i8;
import 'package:software_project/features/audio_upload_and_management/data/services/cloudinary_media_service.dart'
    as _i16;
import 'package:software_project/features/audio_upload_and_management/data/services/file_picker_service.dart'
    as _i29;
import 'package:software_project/features/audio_upload_and_management/data/services/mock_upload_service.dart'
    as _i31;
import 'package:software_project/features/audio_upload_and_management/data/services/upload_waveform_service.dart'
    as _i32;
import 'package:software_project/features/audio_upload_and_management/domain/entities/artist_tools_quota.dart'
    as _i14;
import 'package:software_project/features/audio_upload_and_management/domain/entities/picked_upload_file.dart'
    as _i27;
import 'package:software_project/features/audio_upload_and_management/domain/entities/track_metadata.dart'
    as _i28;
import 'package:software_project/features/audio_upload_and_management/domain/entities/upload_cancellation_token.dart'
    as _i22;
import 'package:software_project/features/audio_upload_and_management/domain/entities/upload_item.dart'
    as _i15;
import 'package:software_project/features/audio_upload_and_management/domain/entities/upload_quota.dart'
    as _i12;
import 'package:software_project/features/audio_upload_and_management/domain/entities/uploaded_track.dart'
    as _i13;
import 'package:software_project/features/audio_upload_and_management/domain/repositories/library_uploads_repository.dart'
    as _i17;
import 'package:software_project/features/audio_upload_and_management/domain/repositories/upload_repository.dart'
    as _i26;
import 'package:software_project/features/audio_upload_and_management/domain/usecases/delete_upload_usecase.dart'
    as _i35;
import 'package:software_project/features/audio_upload_and_management/domain/usecases/get_artist_tools_quota_usecase.dart'
    as _i34;
import 'package:software_project/features/audio_upload_and_management/domain/usecases/get_my_uploads_usecase.dart'
    as _i33;
import 'package:software_project/features/audio_upload_and_management/domain/usecases/replace_file_usecase.dart'
    as _i36;
import 'package:software_project/features/audio_upload_and_management/domain/usecases/update_upload_usecase.dart'
    as _i37;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeBaseOptions_0 extends _i1.SmartFake implements _i2.BaseOptions {
  _FakeBaseOptions_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeInterceptors_1 extends _i1.SmartFake implements _i3.Interceptors {
  _FakeInterceptors_1(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeHttpClientAdapter_2 extends _i1.SmartFake
    implements _i4.HttpClientAdapter {
  _FakeHttpClientAdapter_2(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeTransformer_3 extends _i1.SmartFake implements _i5.Transformer {
  _FakeTransformer_3(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeResponse_4<T1> extends _i1.SmartFake implements _i6.Response<T1> {
  _FakeResponse_4(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeDio_5 extends _i1.SmartFake implements _i7.Dio {
  _FakeDio_5(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeUploadQuotaDto_6 extends _i1.SmartFake
    implements _i8.UploadQuotaDto {
  _FakeUploadQuotaDto_6(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeTrackResponseDto_7 extends _i1.SmartFake
    implements _i9.TrackResponseDto {
  _FakeTrackResponseDto_7(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeArtistToolsQuotaDto_8 extends _i1.SmartFake
    implements _i10.ArtistToolsQuotaDto {
  _FakeArtistToolsQuotaDto_8(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeUploadItemDto_9 extends _i1.SmartFake implements _i11.UploadItemDto {
  _FakeUploadItemDto_9(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeUploadQuota_10 extends _i1.SmartFake implements _i12.UploadQuota {
  _FakeUploadQuota_10(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeUploadedTrack_11 extends _i1.SmartFake
    implements _i13.UploadedTrack {
  _FakeUploadedTrack_11(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeArtistToolsQuota_12 extends _i1.SmartFake
    implements _i14.ArtistToolsQuota {
  _FakeArtistToolsQuota_12(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeUploadItem_13 extends _i1.SmartFake implements _i15.UploadItem {
  _FakeUploadItem_13(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeCloudinaryAsset_14 extends _i1.SmartFake
    implements _i16.CloudinaryAsset {
  _FakeCloudinaryAsset_14(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeLibraryUploadsRepository_15 extends _i1.SmartFake
    implements _i17.LibraryUploadsRepository {
  _FakeLibraryUploadsRepository_15(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [Dio].
///
/// See the documentation for Mockito's code generation for more information.
class MockDio extends _i1.Mock implements _i7.Dio {
  MockDio() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.BaseOptions get options =>
      (super.noSuchMethod(
            Invocation.getter(#options),
            returnValue: _FakeBaseOptions_0(this, Invocation.getter(#options)),
          )
          as _i2.BaseOptions);

  @override
  _i3.Interceptors get interceptors =>
      (super.noSuchMethod(
            Invocation.getter(#interceptors),
            returnValue: _FakeInterceptors_1(
              this,
              Invocation.getter(#interceptors),
            ),
          )
          as _i3.Interceptors);

  @override
  _i4.HttpClientAdapter get httpClientAdapter =>
      (super.noSuchMethod(
            Invocation.getter(#httpClientAdapter),
            returnValue: _FakeHttpClientAdapter_2(
              this,
              Invocation.getter(#httpClientAdapter),
            ),
          )
          as _i4.HttpClientAdapter);

  @override
  _i5.Transformer get transformer =>
      (super.noSuchMethod(
            Invocation.getter(#transformer),
            returnValue: _FakeTransformer_3(
              this,
              Invocation.getter(#transformer),
            ),
          )
          as _i5.Transformer);

  @override
  set options(_i2.BaseOptions? value) => super.noSuchMethod(
    Invocation.setter(#options, value),
    returnValueForMissingStub: null,
  );

  @override
  set httpClientAdapter(_i4.HttpClientAdapter? value) => super.noSuchMethod(
    Invocation.setter(#httpClientAdapter, value),
    returnValueForMissingStub: null,
  );

  @override
  set transformer(_i5.Transformer? value) => super.noSuchMethod(
    Invocation.setter(#transformer, value),
    returnValueForMissingStub: null,
  );

  @override
  void close({bool? force = false}) => super.noSuchMethod(
    Invocation.method(#close, [], {#force: force}),
    returnValueForMissingStub: null,
  );

  @override
  _i18.Future<_i6.Response<T>> head<T>(
    String? path, {
    Object? data,
    Map<String, dynamic>? queryParameters,
    _i2.Options? options,
    _i19.CancelToken? cancelToken,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #head,
              [path],
              {
                #data: data,
                #queryParameters: queryParameters,
                #options: options,
                #cancelToken: cancelToken,
              },
            ),
            returnValue: _i18.Future<_i6.Response<T>>.value(
              _FakeResponse_4<T>(
                this,
                Invocation.method(
                  #head,
                  [path],
                  {
                    #data: data,
                    #queryParameters: queryParameters,
                    #options: options,
                    #cancelToken: cancelToken,
                  },
                ),
              ),
            ),
          )
          as _i18.Future<_i6.Response<T>>);

  @override
  _i18.Future<_i6.Response<T>> headUri<T>(
    Uri? uri, {
    Object? data,
    _i2.Options? options,
    _i19.CancelToken? cancelToken,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #headUri,
              [uri],
              {#data: data, #options: options, #cancelToken: cancelToken},
            ),
            returnValue: _i18.Future<_i6.Response<T>>.value(
              _FakeResponse_4<T>(
                this,
                Invocation.method(
                  #headUri,
                  [uri],
                  {#data: data, #options: options, #cancelToken: cancelToken},
                ),
              ),
            ),
          )
          as _i18.Future<_i6.Response<T>>);

  @override
  _i18.Future<_i6.Response<T>> get<T>(
    String? path, {
    Object? data,
    Map<String, dynamic>? queryParameters,
    _i2.Options? options,
    _i19.CancelToken? cancelToken,
    _i2.ProgressCallback? onReceiveProgress,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #get,
              [path],
              {
                #data: data,
                #queryParameters: queryParameters,
                #options: options,
                #cancelToken: cancelToken,
                #onReceiveProgress: onReceiveProgress,
              },
            ),
            returnValue: _i18.Future<_i6.Response<T>>.value(
              _FakeResponse_4<T>(
                this,
                Invocation.method(
                  #get,
                  [path],
                  {
                    #data: data,
                    #queryParameters: queryParameters,
                    #options: options,
                    #cancelToken: cancelToken,
                    #onReceiveProgress: onReceiveProgress,
                  },
                ),
              ),
            ),
          )
          as _i18.Future<_i6.Response<T>>);

  @override
  _i18.Future<_i6.Response<T>> getUri<T>(
    Uri? uri, {
    Object? data,
    _i2.Options? options,
    _i19.CancelToken? cancelToken,
    _i2.ProgressCallback? onReceiveProgress,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #getUri,
              [uri],
              {
                #data: data,
                #options: options,
                #cancelToken: cancelToken,
                #onReceiveProgress: onReceiveProgress,
              },
            ),
            returnValue: _i18.Future<_i6.Response<T>>.value(
              _FakeResponse_4<T>(
                this,
                Invocation.method(
                  #getUri,
                  [uri],
                  {
                    #data: data,
                    #options: options,
                    #cancelToken: cancelToken,
                    #onReceiveProgress: onReceiveProgress,
                  },
                ),
              ),
            ),
          )
          as _i18.Future<_i6.Response<T>>);

  @override
  _i18.Future<_i6.Response<T>> post<T>(
    String? path, {
    Object? data,
    Map<String, dynamic>? queryParameters,
    _i2.Options? options,
    _i19.CancelToken? cancelToken,
    _i2.ProgressCallback? onSendProgress,
    _i2.ProgressCallback? onReceiveProgress,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #post,
              [path],
              {
                #data: data,
                #queryParameters: queryParameters,
                #options: options,
                #cancelToken: cancelToken,
                #onSendProgress: onSendProgress,
                #onReceiveProgress: onReceiveProgress,
              },
            ),
            returnValue: _i18.Future<_i6.Response<T>>.value(
              _FakeResponse_4<T>(
                this,
                Invocation.method(
                  #post,
                  [path],
                  {
                    #data: data,
                    #queryParameters: queryParameters,
                    #options: options,
                    #cancelToken: cancelToken,
                    #onSendProgress: onSendProgress,
                    #onReceiveProgress: onReceiveProgress,
                  },
                ),
              ),
            ),
          )
          as _i18.Future<_i6.Response<T>>);

  @override
  _i18.Future<_i6.Response<T>> postUri<T>(
    Uri? uri, {
    Object? data,
    _i2.Options? options,
    _i19.CancelToken? cancelToken,
    _i2.ProgressCallback? onSendProgress,
    _i2.ProgressCallback? onReceiveProgress,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #postUri,
              [uri],
              {
                #data: data,
                #options: options,
                #cancelToken: cancelToken,
                #onSendProgress: onSendProgress,
                #onReceiveProgress: onReceiveProgress,
              },
            ),
            returnValue: _i18.Future<_i6.Response<T>>.value(
              _FakeResponse_4<T>(
                this,
                Invocation.method(
                  #postUri,
                  [uri],
                  {
                    #data: data,
                    #options: options,
                    #cancelToken: cancelToken,
                    #onSendProgress: onSendProgress,
                    #onReceiveProgress: onReceiveProgress,
                  },
                ),
              ),
            ),
          )
          as _i18.Future<_i6.Response<T>>);

  @override
  _i18.Future<_i6.Response<T>> put<T>(
    String? path, {
    Object? data,
    Map<String, dynamic>? queryParameters,
    _i2.Options? options,
    _i19.CancelToken? cancelToken,
    _i2.ProgressCallback? onSendProgress,
    _i2.ProgressCallback? onReceiveProgress,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #put,
              [path],
              {
                #data: data,
                #queryParameters: queryParameters,
                #options: options,
                #cancelToken: cancelToken,
                #onSendProgress: onSendProgress,
                #onReceiveProgress: onReceiveProgress,
              },
            ),
            returnValue: _i18.Future<_i6.Response<T>>.value(
              _FakeResponse_4<T>(
                this,
                Invocation.method(
                  #put,
                  [path],
                  {
                    #data: data,
                    #queryParameters: queryParameters,
                    #options: options,
                    #cancelToken: cancelToken,
                    #onSendProgress: onSendProgress,
                    #onReceiveProgress: onReceiveProgress,
                  },
                ),
              ),
            ),
          )
          as _i18.Future<_i6.Response<T>>);

  @override
  _i18.Future<_i6.Response<T>> putUri<T>(
    Uri? uri, {
    Object? data,
    _i2.Options? options,
    _i19.CancelToken? cancelToken,
    _i2.ProgressCallback? onSendProgress,
    _i2.ProgressCallback? onReceiveProgress,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #putUri,
              [uri],
              {
                #data: data,
                #options: options,
                #cancelToken: cancelToken,
                #onSendProgress: onSendProgress,
                #onReceiveProgress: onReceiveProgress,
              },
            ),
            returnValue: _i18.Future<_i6.Response<T>>.value(
              _FakeResponse_4<T>(
                this,
                Invocation.method(
                  #putUri,
                  [uri],
                  {
                    #data: data,
                    #options: options,
                    #cancelToken: cancelToken,
                    #onSendProgress: onSendProgress,
                    #onReceiveProgress: onReceiveProgress,
                  },
                ),
              ),
            ),
          )
          as _i18.Future<_i6.Response<T>>);

  @override
  _i18.Future<_i6.Response<T>> patch<T>(
    String? path, {
    Object? data,
    Map<String, dynamic>? queryParameters,
    _i2.Options? options,
    _i19.CancelToken? cancelToken,
    _i2.ProgressCallback? onSendProgress,
    _i2.ProgressCallback? onReceiveProgress,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #patch,
              [path],
              {
                #data: data,
                #queryParameters: queryParameters,
                #options: options,
                #cancelToken: cancelToken,
                #onSendProgress: onSendProgress,
                #onReceiveProgress: onReceiveProgress,
              },
            ),
            returnValue: _i18.Future<_i6.Response<T>>.value(
              _FakeResponse_4<T>(
                this,
                Invocation.method(
                  #patch,
                  [path],
                  {
                    #data: data,
                    #queryParameters: queryParameters,
                    #options: options,
                    #cancelToken: cancelToken,
                    #onSendProgress: onSendProgress,
                    #onReceiveProgress: onReceiveProgress,
                  },
                ),
              ),
            ),
          )
          as _i18.Future<_i6.Response<T>>);

  @override
  _i18.Future<_i6.Response<T>> patchUri<T>(
    Uri? uri, {
    Object? data,
    _i2.Options? options,
    _i19.CancelToken? cancelToken,
    _i2.ProgressCallback? onSendProgress,
    _i2.ProgressCallback? onReceiveProgress,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #patchUri,
              [uri],
              {
                #data: data,
                #options: options,
                #cancelToken: cancelToken,
                #onSendProgress: onSendProgress,
                #onReceiveProgress: onReceiveProgress,
              },
            ),
            returnValue: _i18.Future<_i6.Response<T>>.value(
              _FakeResponse_4<T>(
                this,
                Invocation.method(
                  #patchUri,
                  [uri],
                  {
                    #data: data,
                    #options: options,
                    #cancelToken: cancelToken,
                    #onSendProgress: onSendProgress,
                    #onReceiveProgress: onReceiveProgress,
                  },
                ),
              ),
            ),
          )
          as _i18.Future<_i6.Response<T>>);

  @override
  _i18.Future<_i6.Response<T>> delete<T>(
    String? path, {
    Object? data,
    Map<String, dynamic>? queryParameters,
    _i2.Options? options,
    _i19.CancelToken? cancelToken,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #delete,
              [path],
              {
                #data: data,
                #queryParameters: queryParameters,
                #options: options,
                #cancelToken: cancelToken,
              },
            ),
            returnValue: _i18.Future<_i6.Response<T>>.value(
              _FakeResponse_4<T>(
                this,
                Invocation.method(
                  #delete,
                  [path],
                  {
                    #data: data,
                    #queryParameters: queryParameters,
                    #options: options,
                    #cancelToken: cancelToken,
                  },
                ),
              ),
            ),
          )
          as _i18.Future<_i6.Response<T>>);

  @override
  _i18.Future<_i6.Response<T>> deleteUri<T>(
    Uri? uri, {
    Object? data,
    _i2.Options? options,
    _i19.CancelToken? cancelToken,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #deleteUri,
              [uri],
              {#data: data, #options: options, #cancelToken: cancelToken},
            ),
            returnValue: _i18.Future<_i6.Response<T>>.value(
              _FakeResponse_4<T>(
                this,
                Invocation.method(
                  #deleteUri,
                  [uri],
                  {#data: data, #options: options, #cancelToken: cancelToken},
                ),
              ),
            ),
          )
          as _i18.Future<_i6.Response<T>>);

  @override
  _i18.Future<_i6.Response<dynamic>> download(
    String? urlPath,
    dynamic savePath, {
    _i2.ProgressCallback? onReceiveProgress,
    Map<String, dynamic>? queryParameters,
    _i19.CancelToken? cancelToken,
    bool? deleteOnError = true,
    _i2.FileAccessMode? fileAccessMode = _i2.FileAccessMode.write,
    String? lengthHeader = 'content-length',
    Object? data,
    _i2.Options? options,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #download,
              [urlPath, savePath],
              {
                #onReceiveProgress: onReceiveProgress,
                #queryParameters: queryParameters,
                #cancelToken: cancelToken,
                #deleteOnError: deleteOnError,
                #fileAccessMode: fileAccessMode,
                #lengthHeader: lengthHeader,
                #data: data,
                #options: options,
              },
            ),
            returnValue: _i18.Future<_i6.Response<dynamic>>.value(
              _FakeResponse_4<dynamic>(
                this,
                Invocation.method(
                  #download,
                  [urlPath, savePath],
                  {
                    #onReceiveProgress: onReceiveProgress,
                    #queryParameters: queryParameters,
                    #cancelToken: cancelToken,
                    #deleteOnError: deleteOnError,
                    #fileAccessMode: fileAccessMode,
                    #lengthHeader: lengthHeader,
                    #data: data,
                    #options: options,
                  },
                ),
              ),
            ),
          )
          as _i18.Future<_i6.Response<dynamic>>);

  @override
  _i18.Future<_i6.Response<dynamic>> downloadUri(
    Uri? uri,
    dynamic savePath, {
    _i2.ProgressCallback? onReceiveProgress,
    _i19.CancelToken? cancelToken,
    bool? deleteOnError = true,
    _i2.FileAccessMode? fileAccessMode = _i2.FileAccessMode.write,
    String? lengthHeader = 'content-length',
    Object? data,
    _i2.Options? options,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #downloadUri,
              [uri, savePath],
              {
                #onReceiveProgress: onReceiveProgress,
                #cancelToken: cancelToken,
                #deleteOnError: deleteOnError,
                #fileAccessMode: fileAccessMode,
                #lengthHeader: lengthHeader,
                #data: data,
                #options: options,
              },
            ),
            returnValue: _i18.Future<_i6.Response<dynamic>>.value(
              _FakeResponse_4<dynamic>(
                this,
                Invocation.method(
                  #downloadUri,
                  [uri, savePath],
                  {
                    #onReceiveProgress: onReceiveProgress,
                    #cancelToken: cancelToken,
                    #deleteOnError: deleteOnError,
                    #fileAccessMode: fileAccessMode,
                    #lengthHeader: lengthHeader,
                    #data: data,
                    #options: options,
                  },
                ),
              ),
            ),
          )
          as _i18.Future<_i6.Response<dynamic>>);

  @override
  _i18.Future<_i6.Response<T>> request<T>(
    String? url, {
    Object? data,
    Map<String, dynamic>? queryParameters,
    _i19.CancelToken? cancelToken,
    _i2.Options? options,
    _i2.ProgressCallback? onSendProgress,
    _i2.ProgressCallback? onReceiveProgress,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #request,
              [url],
              {
                #data: data,
                #queryParameters: queryParameters,
                #cancelToken: cancelToken,
                #options: options,
                #onSendProgress: onSendProgress,
                #onReceiveProgress: onReceiveProgress,
              },
            ),
            returnValue: _i18.Future<_i6.Response<T>>.value(
              _FakeResponse_4<T>(
                this,
                Invocation.method(
                  #request,
                  [url],
                  {
                    #data: data,
                    #queryParameters: queryParameters,
                    #cancelToken: cancelToken,
                    #options: options,
                    #onSendProgress: onSendProgress,
                    #onReceiveProgress: onReceiveProgress,
                  },
                ),
              ),
            ),
          )
          as _i18.Future<_i6.Response<T>>);

  @override
  _i18.Future<_i6.Response<T>> requestUri<T>(
    Uri? uri, {
    Object? data,
    _i19.CancelToken? cancelToken,
    _i2.Options? options,
    _i2.ProgressCallback? onSendProgress,
    _i2.ProgressCallback? onReceiveProgress,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #requestUri,
              [uri],
              {
                #data: data,
                #cancelToken: cancelToken,
                #options: options,
                #onSendProgress: onSendProgress,
                #onReceiveProgress: onReceiveProgress,
              },
            ),
            returnValue: _i18.Future<_i6.Response<T>>.value(
              _FakeResponse_4<T>(
                this,
                Invocation.method(
                  #requestUri,
                  [uri],
                  {
                    #data: data,
                    #cancelToken: cancelToken,
                    #options: options,
                    #onSendProgress: onSendProgress,
                    #onReceiveProgress: onReceiveProgress,
                  },
                ),
              ),
            ),
          )
          as _i18.Future<_i6.Response<T>>);

  @override
  _i18.Future<_i6.Response<T>> fetch<T>(_i2.RequestOptions? requestOptions) =>
      (super.noSuchMethod(
            Invocation.method(#fetch, [requestOptions]),
            returnValue: _i18.Future<_i6.Response<T>>.value(
              _FakeResponse_4<T>(
                this,
                Invocation.method(#fetch, [requestOptions]),
              ),
            ),
          )
          as _i18.Future<_i6.Response<T>>);

  @override
  _i7.Dio clone({
    _i2.BaseOptions? options,
    _i3.Interceptors? interceptors,
    _i4.HttpClientAdapter? httpClientAdapter,
    _i5.Transformer? transformer,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#clone, [], {
              #options: options,
              #interceptors: interceptors,
              #httpClientAdapter: httpClientAdapter,
              #transformer: transformer,
            }),
            returnValue: _FakeDio_5(
              this,
              Invocation.method(#clone, [], {
                #options: options,
                #interceptors: interceptors,
                #httpClientAdapter: httpClientAdapter,
                #transformer: transformer,
              }),
            ),
          )
          as _i7.Dio);
}

/// A class which mocks [UploadApi].
///
/// See the documentation for Mockito's code generation for more information.
class MockUploadApi extends _i1.Mock implements _i20.UploadApi {
  MockUploadApi() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i7.Dio get dio =>
      (super.noSuchMethod(
            Invocation.getter(#dio),
            returnValue: _FakeDio_5(this, Invocation.getter(#dio)),
          )
          as _i7.Dio);

  @override
  _i18.Future<_i8.UploadQuotaDto> getUploadQuota(String? userId) =>
      (super.noSuchMethod(
            Invocation.method(#getUploadQuota, [userId]),
            returnValue: _i18.Future<_i8.UploadQuotaDto>.value(
              _FakeUploadQuotaDto_6(
                this,
                Invocation.method(#getUploadQuota, [userId]),
              ),
            ),
          )
          as _i18.Future<_i8.UploadQuotaDto>);

  @override
  _i18.Future<_i9.TrackResponseDto> createTrack(
    _i21.CreateTrackRequestDto? request,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#createTrack, [request]),
            returnValue: _i18.Future<_i9.TrackResponseDto>.value(
              _FakeTrackResponseDto_7(
                this,
                Invocation.method(#createTrack, [request]),
              ),
            ),
          )
          as _i18.Future<_i9.TrackResponseDto>);

  @override
  _i18.Future<_i9.TrackResponseDto> uploadAudio({
    required String? trackId,
    required String? filePath,
    required String? fileName,
    required _i2.ProgressCallback? onSendProgress,
    _i22.UploadCancellationToken? cancellationToken,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#uploadAudio, [], {
              #trackId: trackId,
              #filePath: filePath,
              #fileName: fileName,
              #onSendProgress: onSendProgress,
              #cancellationToken: cancellationToken,
            }),
            returnValue: _i18.Future<_i9.TrackResponseDto>.value(
              _FakeTrackResponseDto_7(
                this,
                Invocation.method(#uploadAudio, [], {
                  #trackId: trackId,
                  #filePath: filePath,
                  #fileName: fileName,
                  #onSendProgress: onSendProgress,
                  #cancellationToken: cancellationToken,
                }),
              ),
            ),
          )
          as _i18.Future<_i9.TrackResponseDto>);

  @override
  _i18.Future<_i9.TrackResponseDto> replaceAudio({
    required String? trackId,
    required String? filePath,
    required String? fileName,
    required _i2.ProgressCallback? onSendProgress,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#replaceAudio, [], {
              #trackId: trackId,
              #filePath: filePath,
              #fileName: fileName,
              #onSendProgress: onSendProgress,
            }),
            returnValue: _i18.Future<_i9.TrackResponseDto>.value(
              _FakeTrackResponseDto_7(
                this,
                Invocation.method(#replaceAudio, [], {
                  #trackId: trackId,
                  #filePath: filePath,
                  #fileName: fileName,
                  #onSendProgress: onSendProgress,
                }),
              ),
            ),
          )
          as _i18.Future<_i9.TrackResponseDto>);

  @override
  _i18.Future<_i9.TrackResponseDto> finalizeMetadata(
    _i23.FinalizeTrackMetadataRequestDto? request,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#finalizeMetadata, [request]),
            returnValue: _i18.Future<_i9.TrackResponseDto>.value(
              _FakeTrackResponseDto_7(
                this,
                Invocation.method(#finalizeMetadata, [request]),
              ),
            ),
          )
          as _i18.Future<_i9.TrackResponseDto>);

  @override
  _i18.Future<_i9.TrackResponseDto> getTrackStatus(String? trackId) =>
      (super.noSuchMethod(
            Invocation.method(#getTrackStatus, [trackId]),
            returnValue: _i18.Future<_i9.TrackResponseDto>.value(
              _FakeTrackResponseDto_7(
                this,
                Invocation.method(#getTrackStatus, [trackId]),
              ),
            ),
          )
          as _i18.Future<_i9.TrackResponseDto>);

  @override
  _i18.Future<_i9.TrackResponseDto> getTrackDetails(String? trackId) =>
      (super.noSuchMethod(
            Invocation.method(#getTrackDetails, [trackId]),
            returnValue: _i18.Future<_i9.TrackResponseDto>.value(
              _FakeTrackResponseDto_7(
                this,
                Invocation.method(#getTrackDetails, [trackId]),
              ),
            ),
          )
          as _i18.Future<_i9.TrackResponseDto>);

  @override
  _i18.Future<_i9.TrackResponseDto> updateTrackMetadata(
    _i23.FinalizeTrackMetadataRequestDto? request,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#updateTrackMetadata, [request]),
            returnValue: _i18.Future<_i9.TrackResponseDto>.value(
              _FakeTrackResponseDto_7(
                this,
                Invocation.method(#updateTrackMetadata, [request]),
              ),
            ),
          )
          as _i18.Future<_i9.TrackResponseDto>);

  @override
  _i18.Future<void> deleteTrack(String? trackId) =>
      (super.noSuchMethod(
            Invocation.method(#deleteTrack, [trackId]),
            returnValue: _i18.Future<void>.value(),
            returnValueForMissingStub: _i18.Future<void>.value(),
          )
          as _i18.Future<void>);
}

/// A class which mocks [LibraryUploadsApi].
///
/// See the documentation for Mockito's code generation for more information.
class MockLibraryUploadsApi extends _i1.Mock implements _i24.LibraryUploadsApi {
  MockLibraryUploadsApi() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i7.Dio get dio =>
      (super.noSuchMethod(
            Invocation.getter(#dio),
            returnValue: _FakeDio_5(this, Invocation.getter(#dio)),
          )
          as _i7.Dio);

  @override
  _i18.Future<List<_i11.UploadItemDto>> getMyUploads() =>
      (super.noSuchMethod(
            Invocation.method(#getMyUploads, []),
            returnValue: _i18.Future<List<_i11.UploadItemDto>>.value(
              <_i11.UploadItemDto>[],
            ),
          )
          as _i18.Future<List<_i11.UploadItemDto>>);

  @override
  _i18.Future<_i10.ArtistToolsQuotaDto> getArtistToolsQuota() =>
      (super.noSuchMethod(
            Invocation.method(#getArtistToolsQuota, []),
            returnValue: _i18.Future<_i10.ArtistToolsQuotaDto>.value(
              _FakeArtistToolsQuotaDto_8(
                this,
                Invocation.method(#getArtistToolsQuota, []),
              ),
            ),
          )
          as _i18.Future<_i10.ArtistToolsQuotaDto>);

  @override
  _i18.Future<void> deleteUpload(String? trackId) =>
      (super.noSuchMethod(
            Invocation.method(#deleteUpload, [trackId]),
            returnValue: _i18.Future<void>.value(),
            returnValueForMissingStub: _i18.Future<void>.value(),
          )
          as _i18.Future<void>);

  @override
  _i18.Future<void> replaceUploadFile({
    required String? trackId,
    required String? filePath,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#replaceUploadFile, [], {
              #trackId: trackId,
              #filePath: filePath,
            }),
            returnValue: _i18.Future<void>.value(),
            returnValueForMissingStub: _i18.Future<void>.value(),
          )
          as _i18.Future<void>);

  @override
  _i18.Future<_i11.UploadItemDto> updateUpload({
    required String? trackId,
    required String? title,
    required String? description,
    required String? privacy,
    String? localArtworkPath,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#updateUpload, [], {
              #trackId: trackId,
              #title: title,
              #description: description,
              #privacy: privacy,
              #localArtworkPath: localArtworkPath,
            }),
            returnValue: _i18.Future<_i11.UploadItemDto>.value(
              _FakeUploadItemDto_9(
                this,
                Invocation.method(#updateUpload, [], {
                  #trackId: trackId,
                  #title: title,
                  #description: description,
                  #privacy: privacy,
                  #localArtworkPath: localArtworkPath,
                }),
              ),
            ),
          )
          as _i18.Future<_i11.UploadItemDto>);
}

/// A class which mocks [MockLibraryUploadsApi].
///
/// See the documentation for Mockito's code generation for more information.
class MockMockLibraryUploadsApi extends _i1.Mock
    implements _i25.MockLibraryUploadsApi {
  MockMockLibraryUploadsApi() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i18.Future<List<_i11.UploadItemDto>> getMyUploads() =>
      (super.noSuchMethod(
            Invocation.method(#getMyUploads, []),
            returnValue: _i18.Future<List<_i11.UploadItemDto>>.value(
              <_i11.UploadItemDto>[],
            ),
          )
          as _i18.Future<List<_i11.UploadItemDto>>);

  @override
  _i18.Future<_i10.ArtistToolsQuotaDto> getArtistToolsQuota() =>
      (super.noSuchMethod(
            Invocation.method(#getArtistToolsQuota, []),
            returnValue: _i18.Future<_i10.ArtistToolsQuotaDto>.value(
              _FakeArtistToolsQuotaDto_8(
                this,
                Invocation.method(#getArtistToolsQuota, []),
              ),
            ),
          )
          as _i18.Future<_i10.ArtistToolsQuotaDto>);

  @override
  _i18.Future<void> deleteUpload(String? trackId) =>
      (super.noSuchMethod(
            Invocation.method(#deleteUpload, [trackId]),
            returnValue: _i18.Future<void>.value(),
            returnValueForMissingStub: _i18.Future<void>.value(),
          )
          as _i18.Future<void>);

  @override
  _i18.Future<void> replaceUploadFile({
    required String? trackId,
    required String? filePath,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#replaceUploadFile, [], {
              #trackId: trackId,
              #filePath: filePath,
            }),
            returnValue: _i18.Future<void>.value(),
            returnValueForMissingStub: _i18.Future<void>.value(),
          )
          as _i18.Future<void>);

  @override
  _i18.Future<_i11.UploadItemDto> updateUpload({
    required String? trackId,
    required String? title,
    required String? description,
    required String? privacy,
    String? localArtworkPath,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#updateUpload, [], {
              #trackId: trackId,
              #title: title,
              #description: description,
              #privacy: privacy,
              #localArtworkPath: localArtworkPath,
            }),
            returnValue: _i18.Future<_i11.UploadItemDto>.value(
              _FakeUploadItemDto_9(
                this,
                Invocation.method(#updateUpload, [], {
                  #trackId: trackId,
                  #title: title,
                  #description: description,
                  #privacy: privacy,
                  #localArtworkPath: localArtworkPath,
                }),
              ),
            ),
          )
          as _i18.Future<_i11.UploadItemDto>);
}

/// A class which mocks [UploadRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockUploadRepository extends _i1.Mock implements _i26.UploadRepository {
  MockUploadRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i18.Future<_i12.UploadQuota> getUploadQuota(String? userId) =>
      (super.noSuchMethod(
            Invocation.method(#getUploadQuota, [userId]),
            returnValue: _i18.Future<_i12.UploadQuota>.value(
              _FakeUploadQuota_10(
                this,
                Invocation.method(#getUploadQuota, [userId]),
              ),
            ),
          )
          as _i18.Future<_i12.UploadQuota>);

  @override
  _i18.Future<_i13.UploadedTrack> createTrack(String? userId) =>
      (super.noSuchMethod(
            Invocation.method(#createTrack, [userId]),
            returnValue: _i18.Future<_i13.UploadedTrack>.value(
              _FakeUploadedTrack_11(
                this,
                Invocation.method(#createTrack, [userId]),
              ),
            ),
          )
          as _i18.Future<_i13.UploadedTrack>);

  @override
  _i18.Future<_i13.UploadedTrack> uploadAudio({
    required String? trackId,
    required _i27.PickedUploadFile? file,
    required void Function(double)? onProgress,
    _i22.UploadCancellationToken? cancellationToken,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#uploadAudio, [], {
              #trackId: trackId,
              #file: file,
              #onProgress: onProgress,
              #cancellationToken: cancellationToken,
            }),
            returnValue: _i18.Future<_i13.UploadedTrack>.value(
              _FakeUploadedTrack_11(
                this,
                Invocation.method(#uploadAudio, [], {
                  #trackId: trackId,
                  #file: file,
                  #onProgress: onProgress,
                  #cancellationToken: cancellationToken,
                }),
              ),
            ),
          )
          as _i18.Future<_i13.UploadedTrack>);

  @override
  _i18.Future<_i13.UploadedTrack> finalizeMetadata({
    required String? trackId,
    required _i28.TrackMetadata? metadata,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#finalizeMetadata, [], {
              #trackId: trackId,
              #metadata: metadata,
            }),
            returnValue: _i18.Future<_i13.UploadedTrack>.value(
              _FakeUploadedTrack_11(
                this,
                Invocation.method(#finalizeMetadata, [], {
                  #trackId: trackId,
                  #metadata: metadata,
                }),
              ),
            ),
          )
          as _i18.Future<_i13.UploadedTrack>);

  @override
  _i18.Future<_i13.UploadedTrack> waitUntilProcessed(String? trackId) =>
      (super.noSuchMethod(
            Invocation.method(#waitUntilProcessed, [trackId]),
            returnValue: _i18.Future<_i13.UploadedTrack>.value(
              _FakeUploadedTrack_11(
                this,
                Invocation.method(#waitUntilProcessed, [trackId]),
              ),
            ),
          )
          as _i18.Future<_i13.UploadedTrack>);

  @override
  _i18.Future<_i13.UploadedTrack> getTrackDetails(String? trackId) =>
      (super.noSuchMethod(
            Invocation.method(#getTrackDetails, [trackId]),
            returnValue: _i18.Future<_i13.UploadedTrack>.value(
              _FakeUploadedTrack_11(
                this,
                Invocation.method(#getTrackDetails, [trackId]),
              ),
            ),
          )
          as _i18.Future<_i13.UploadedTrack>);

  @override
  _i18.Future<_i13.UploadedTrack> updateTrackMetadata({
    required String? trackId,
    required _i28.TrackMetadata? metadata,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#updateTrackMetadata, [], {
              #trackId: trackId,
              #metadata: metadata,
            }),
            returnValue: _i18.Future<_i13.UploadedTrack>.value(
              _FakeUploadedTrack_11(
                this,
                Invocation.method(#updateTrackMetadata, [], {
                  #trackId: trackId,
                  #metadata: metadata,
                }),
              ),
            ),
          )
          as _i18.Future<_i13.UploadedTrack>);

  @override
  _i18.Future<void> deleteTrack(String? trackId) =>
      (super.noSuchMethod(
            Invocation.method(#deleteTrack, [trackId]),
            returnValue: _i18.Future<void>.value(),
            returnValueForMissingStub: _i18.Future<void>.value(),
          )
          as _i18.Future<void>);
}

/// A class which mocks [LibraryUploadsRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockLibraryUploadsRepository extends _i1.Mock
    implements _i17.LibraryUploadsRepository {
  MockLibraryUploadsRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i18.Future<List<_i15.UploadItem>> getMyUploads() =>
      (super.noSuchMethod(
            Invocation.method(#getMyUploads, []),
            returnValue: _i18.Future<List<_i15.UploadItem>>.value(
              <_i15.UploadItem>[],
            ),
          )
          as _i18.Future<List<_i15.UploadItem>>);

  @override
  _i18.Future<_i14.ArtistToolsQuota> getArtistToolsQuota() =>
      (super.noSuchMethod(
            Invocation.method(#getArtistToolsQuota, []),
            returnValue: _i18.Future<_i14.ArtistToolsQuota>.value(
              _FakeArtistToolsQuota_12(
                this,
                Invocation.method(#getArtistToolsQuota, []),
              ),
            ),
          )
          as _i18.Future<_i14.ArtistToolsQuota>);

  @override
  _i18.Future<void> deleteUpload(String? trackId) =>
      (super.noSuchMethod(
            Invocation.method(#deleteUpload, [trackId]),
            returnValue: _i18.Future<void>.value(),
            returnValueForMissingStub: _i18.Future<void>.value(),
          )
          as _i18.Future<void>);

  @override
  _i18.Future<void> replaceUploadFile({
    required String? trackId,
    required String? filePath,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#replaceUploadFile, [], {
              #trackId: trackId,
              #filePath: filePath,
            }),
            returnValue: _i18.Future<void>.value(),
            returnValueForMissingStub: _i18.Future<void>.value(),
          )
          as _i18.Future<void>);

  @override
  _i18.Future<_i15.UploadItem> updateUpload({
    required String? trackId,
    required String? title,
    required String? description,
    required String? privacy,
    String? localArtworkPath,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#updateUpload, [], {
              #trackId: trackId,
              #title: title,
              #description: description,
              #privacy: privacy,
              #localArtworkPath: localArtworkPath,
            }),
            returnValue: _i18.Future<_i15.UploadItem>.value(
              _FakeUploadItem_13(
                this,
                Invocation.method(#updateUpload, [], {
                  #trackId: trackId,
                  #title: title,
                  #description: description,
                  #privacy: privacy,
                  #localArtworkPath: localArtworkPath,
                }),
              ),
            ),
          )
          as _i18.Future<_i15.UploadItem>);
}

/// A class which mocks [FilePickerService].
///
/// See the documentation for Mockito's code generation for more information.
class MockFilePickerService extends _i1.Mock implements _i29.FilePickerService {
  MockFilePickerService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i18.Future<_i27.PickedUploadFile?> pickAudioFile() =>
      (super.noSuchMethod(
            Invocation.method(#pickAudioFile, []),
            returnValue: _i18.Future<_i27.PickedUploadFile?>.value(),
          )
          as _i18.Future<_i27.PickedUploadFile?>);

  @override
  _i18.Future<String?> pickArtworkImage({bool? fromCamera = false}) =>
      (super.noSuchMethod(
            Invocation.method(#pickArtworkImage, [], {#fromCamera: fromCamera}),
            returnValue: _i18.Future<String?>.value(),
          )
          as _i18.Future<String?>);
}

/// A class which mocks [CloudinaryMediaService].
///
/// See the documentation for Mockito's code generation for more information.
class MockCloudinaryMediaService extends _i1.Mock
    implements _i16.CloudinaryMediaService {
  MockCloudinaryMediaService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  String get apiKey =>
      (super.noSuchMethod(
            Invocation.getter(#apiKey),
            returnValue: _i30.dummyValue<String>(
              this,
              Invocation.getter(#apiKey),
            ),
          )
          as String);

  @override
  String get apiSecret =>
      (super.noSuchMethod(
            Invocation.getter(#apiSecret),
            returnValue: _i30.dummyValue<String>(
              this,
              Invocation.getter(#apiSecret),
            ),
          )
          as String);

  @override
  bool get isConfigured =>
      (super.noSuchMethod(Invocation.getter(#isConfigured), returnValue: false)
          as bool);

  @override
  bool get canDeleteAssets =>
      (super.noSuchMethod(
            Invocation.getter(#canDeleteAssets),
            returnValue: false,
          )
          as bool);

  @override
  _i18.Future<_i16.CloudinaryAsset> uploadAudio({
    required String? filePath,
    required String? fileName,
    required _i2.ProgressCallback? onSendProgress,
    _i22.UploadCancellationToken? cancellationToken,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#uploadAudio, [], {
              #filePath: filePath,
              #fileName: fileName,
              #onSendProgress: onSendProgress,
              #cancellationToken: cancellationToken,
            }),
            returnValue: _i18.Future<_i16.CloudinaryAsset>.value(
              _FakeCloudinaryAsset_14(
                this,
                Invocation.method(#uploadAudio, [], {
                  #filePath: filePath,
                  #fileName: fileName,
                  #onSendProgress: onSendProgress,
                  #cancellationToken: cancellationToken,
                }),
              ),
            ),
          )
          as _i18.Future<_i16.CloudinaryAsset>);

  @override
  _i18.Future<_i16.CloudinaryAsset> uploadArtwork({
    required String? filePath,
    required String? fileName,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#uploadArtwork, [], {
              #filePath: filePath,
              #fileName: fileName,
            }),
            returnValue: _i18.Future<_i16.CloudinaryAsset>.value(
              _FakeCloudinaryAsset_14(
                this,
                Invocation.method(#uploadArtwork, [], {
                  #filePath: filePath,
                  #fileName: fileName,
                }),
              ),
            ),
          )
          as _i18.Future<_i16.CloudinaryAsset>);

  @override
  String buildWaveformImageUrl({
    required String? audioPublicId,
    int? width = 1200,
    int? height = 240,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#buildWaveformImageUrl, [], {
              #audioPublicId: audioPublicId,
              #width: width,
              #height: height,
            }),
            returnValue: _i30.dummyValue<String>(
              this,
              Invocation.method(#buildWaveformImageUrl, [], {
                #audioPublicId: audioPublicId,
                #width: width,
                #height: height,
              }),
            ),
          )
          as String);

  @override
  _i18.Future<void> deleteTrackAssets({String? audioUrl, String? artworkUrl}) =>
      (super.noSuchMethod(
            Invocation.method(#deleteTrackAssets, [], {
              #audioUrl: audioUrl,
              #artworkUrl: artworkUrl,
            }),
            returnValue: _i18.Future<void>.value(),
            returnValueForMissingStub: _i18.Future<void>.value(),
          )
          as _i18.Future<void>);
}

/// A class which mocks [MockUploadService].
///
/// See the documentation for Mockito's code generation for more information.
class MockMockUploadService extends _i1.Mock implements _i31.MockUploadService {
  MockMockUploadService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i18.Future<Map<String, dynamic>> getUploadQuota({required String? userId}) =>
      (super.noSuchMethod(
            Invocation.method(#getUploadQuota, [], {#userId: userId}),
            returnValue: _i18.Future<Map<String, dynamic>>.value(
              <String, dynamic>{},
            ),
          )
          as _i18.Future<Map<String, dynamic>>);

  @override
  _i18.Future<Map<String, dynamic>> createTrack({required String? userId}) =>
      (super.noSuchMethod(
            Invocation.method(#createTrack, [], {#userId: userId}),
            returnValue: _i18.Future<Map<String, dynamic>>.value(
              <String, dynamic>{},
            ),
          )
          as _i18.Future<Map<String, dynamic>>);

  @override
  _i18.Stream<double> uploadProgress() =>
      (super.noSuchMethod(
            Invocation.method(#uploadProgress, []),
            returnValue: _i18.Stream<double>.empty(),
          )
          as _i18.Stream<double>);

  @override
  _i18.Future<Map<String, dynamic>> uploadAudio({
    required String? trackId,
    String? localFilePath,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#uploadAudio, [], {
              #trackId: trackId,
              #localFilePath: localFilePath,
            }),
            returnValue: _i18.Future<Map<String, dynamic>>.value(
              <String, dynamic>{},
            ),
          )
          as _i18.Future<Map<String, dynamic>>);

  @override
  _i18.Future<Map<String, dynamic>> replaceAudio({required String? trackId}) =>
      (super.noSuchMethod(
            Invocation.method(#replaceAudio, [], {#trackId: trackId}),
            returnValue: _i18.Future<Map<String, dynamic>>.value(
              <String, dynamic>{},
            ),
          )
          as _i18.Future<Map<String, dynamic>>);

  @override
  _i18.Future<Map<String, dynamic>> finalizeMetadata({
    required String? trackId,
    required Map<String, dynamic>? metadata,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#finalizeMetadata, [], {
              #trackId: trackId,
              #metadata: metadata,
            }),
            returnValue: _i18.Future<Map<String, dynamic>>.value(
              <String, dynamic>{},
            ),
          )
          as _i18.Future<Map<String, dynamic>>);

  @override
  _i18.Future<Map<String, dynamic>> pollTrackStatus({
    required String? trackId,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#pollTrackStatus, [], {#trackId: trackId}),
            returnValue: _i18.Future<Map<String, dynamic>>.value(
              <String, dynamic>{},
            ),
          )
          as _i18.Future<Map<String, dynamic>>);

  @override
  _i18.Future<Map<String, dynamic>> getTrackDetails({
    required String? trackId,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#getTrackDetails, [], {#trackId: trackId}),
            returnValue: _i18.Future<Map<String, dynamic>>.value(
              <String, dynamic>{},
            ),
          )
          as _i18.Future<Map<String, dynamic>>);

  @override
  _i18.Future<void> deleteTrack({required String? trackId}) =>
      (super.noSuchMethod(
            Invocation.method(#deleteTrack, [], {#trackId: trackId}),
            returnValue: _i18.Future<void>.value(),
            returnValueForMissingStub: _i18.Future<void>.value(),
          )
          as _i18.Future<void>);

  @override
  _i18.Future<Map<String, dynamic>> updateTrackMetadata({
    required String? trackId,
    required Map<String, dynamic>? metadata,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#updateTrackMetadata, [], {
              #trackId: trackId,
              #metadata: metadata,
            }),
            returnValue: _i18.Future<Map<String, dynamic>>.value(
              <String, dynamic>{},
            ),
          )
          as _i18.Future<Map<String, dynamic>>);
}

/// A class which mocks [UploadWaveformService].
///
/// See the documentation for Mockito's code generation for more information.
class MockUploadWaveformService extends _i1.Mock
    implements _i32.UploadWaveformService {
  MockUploadWaveformService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i18.Future<List<double>?> generateDisplayBarsFromFile(
    String? filePath, {
    int? targetBarCount = 180,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #generateDisplayBarsFromFile,
              [filePath],
              {#targetBarCount: targetBarCount},
            ),
            returnValue: _i18.Future<List<double>?>.value(),
          )
          as _i18.Future<List<double>?>);
}

/// A class which mocks [GetMyUploadsUsecase].
///
/// See the documentation for Mockito's code generation for more information.
class MockGetMyUploadsUsecase extends _i1.Mock
    implements _i33.GetMyUploadsUsecase {
  MockGetMyUploadsUsecase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i17.LibraryUploadsRepository get repository =>
      (super.noSuchMethod(
            Invocation.getter(#repository),
            returnValue: _FakeLibraryUploadsRepository_15(
              this,
              Invocation.getter(#repository),
            ),
          )
          as _i17.LibraryUploadsRepository);

  @override
  _i18.Future<List<_i15.UploadItem>> call() =>
      (super.noSuchMethod(
            Invocation.method(#call, []),
            returnValue: _i18.Future<List<_i15.UploadItem>>.value(
              <_i15.UploadItem>[],
            ),
          )
          as _i18.Future<List<_i15.UploadItem>>);
}

/// A class which mocks [GetArtistToolsQuotaUsecase].
///
/// See the documentation for Mockito's code generation for more information.
class MockGetArtistToolsQuotaUsecase extends _i1.Mock
    implements _i34.GetArtistToolsQuotaUsecase {
  MockGetArtistToolsQuotaUsecase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i17.LibraryUploadsRepository get repository =>
      (super.noSuchMethod(
            Invocation.getter(#repository),
            returnValue: _FakeLibraryUploadsRepository_15(
              this,
              Invocation.getter(#repository),
            ),
          )
          as _i17.LibraryUploadsRepository);

  @override
  _i18.Future<_i14.ArtistToolsQuota> call() =>
      (super.noSuchMethod(
            Invocation.method(#call, []),
            returnValue: _i18.Future<_i14.ArtistToolsQuota>.value(
              _FakeArtistToolsQuota_12(this, Invocation.method(#call, [])),
            ),
          )
          as _i18.Future<_i14.ArtistToolsQuota>);
}

/// A class which mocks [DeleteUploadUsecase].
///
/// See the documentation for Mockito's code generation for more information.
class MockDeleteUploadUsecase extends _i1.Mock
    implements _i35.DeleteUploadUsecase {
  MockDeleteUploadUsecase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i17.LibraryUploadsRepository get repository =>
      (super.noSuchMethod(
            Invocation.getter(#repository),
            returnValue: _FakeLibraryUploadsRepository_15(
              this,
              Invocation.getter(#repository),
            ),
          )
          as _i17.LibraryUploadsRepository);

  @override
  _i18.Future<void> call(String? trackId) =>
      (super.noSuchMethod(
            Invocation.method(#call, [trackId]),
            returnValue: _i18.Future<void>.value(),
            returnValueForMissingStub: _i18.Future<void>.value(),
          )
          as _i18.Future<void>);
}

/// A class which mocks [ReplaceFileUsecase].
///
/// See the documentation for Mockito's code generation for more information.
class MockReplaceFileUsecase extends _i1.Mock
    implements _i36.ReplaceFileUsecase {
  MockReplaceFileUsecase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i17.LibraryUploadsRepository get repository =>
      (super.noSuchMethod(
            Invocation.getter(#repository),
            returnValue: _FakeLibraryUploadsRepository_15(
              this,
              Invocation.getter(#repository),
            ),
          )
          as _i17.LibraryUploadsRepository);

  @override
  _i18.Future<void> call({
    required String? trackId,
    required String? filePath,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#call, [], {
              #trackId: trackId,
              #filePath: filePath,
            }),
            returnValue: _i18.Future<void>.value(),
            returnValueForMissingStub: _i18.Future<void>.value(),
          )
          as _i18.Future<void>);
}

/// A class which mocks [UpdateUploadUsecase].
///
/// See the documentation for Mockito's code generation for more information.
class MockUpdateUploadUsecase extends _i1.Mock
    implements _i37.UpdateUploadUsecase {
  MockUpdateUploadUsecase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i17.LibraryUploadsRepository get repository =>
      (super.noSuchMethod(
            Invocation.getter(#repository),
            returnValue: _FakeLibraryUploadsRepository_15(
              this,
              Invocation.getter(#repository),
            ),
          )
          as _i17.LibraryUploadsRepository);

  @override
  _i18.Future<_i15.UploadItem> call({
    required String? trackId,
    required String? title,
    required String? description,
    required String? privacy,
    String? localArtworkPath,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#call, [], {
              #trackId: trackId,
              #title: title,
              #description: description,
              #privacy: privacy,
              #localArtworkPath: localArtworkPath,
            }),
            returnValue: _i18.Future<_i15.UploadItem>.value(
              _FakeUploadItem_13(
                this,
                Invocation.method(#call, [], {
                  #trackId: trackId,
                  #title: title,
                  #description: description,
                  #privacy: privacy,
                  #localArtworkPath: localArtworkPath,
                }),
              ),
            ),
          )
          as _i18.Future<_i15.UploadItem>);
}
