// Mocks generated by Mockito 5.4.6 from annotations
// in software_project/test/features/feed_search_discovery/domain/usecases/search_usecases_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i5;

import 'package:mockito/mockito.dart' as _i1;
import 'package:software_project/features/feed_search_discovery/domain/entities/album_result_entity.dart'
    as _i10;
import 'package:software_project/features/feed_search_discovery/domain/entities/genre_detail_entity.dart'
    as _i3;
import 'package:software_project/features/feed_search_discovery/domain/entities/playlist_result_entity.dart'
    as _i9;
import 'package:software_project/features/feed_search_discovery/domain/entities/profile_result_entity.dart'
    as _i8;
import 'package:software_project/features/feed_search_discovery/domain/entities/search_all_result_entity.dart'
    as _i2;
import 'package:software_project/features/feed_search_discovery/domain/entities/search_filters_entity.dart'
    as _i7;
import 'package:software_project/features/feed_search_discovery/domain/entities/search_genre_entity.dart'
    as _i11;
import 'package:software_project/features/feed_search_discovery/domain/entities/track_result_entity.dart'
    as _i6;
import 'package:software_project/features/feed_search_discovery/domain/repositories/search_repository.dart'
    as _i4;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeSearchAllResultEntity_0 extends _i1.SmartFake
    implements _i2.SearchAllResultEntity {
  _FakeSearchAllResultEntity_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeGenreDetailEntity_1 extends _i1.SmartFake
    implements _i3.GenreDetailEntity {
  _FakeGenreDetailEntity_1(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [SearchRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockSearchRepository extends _i1.Mock implements _i4.SearchRepository {
  @override
  _i5.Future<_i2.SearchAllResultEntity> searchAll(String? query) =>
      (super.noSuchMethod(
            Invocation.method(#searchAll, [query]),
            returnValue: _i5.Future<_i2.SearchAllResultEntity>.value(
              _FakeSearchAllResultEntity_0(
                this,
                Invocation.method(#searchAll, [query]),
              ),
            ),
            returnValueForMissingStub:
                _i5.Future<_i2.SearchAllResultEntity>.value(
                  _FakeSearchAllResultEntity_0(
                    this,
                    Invocation.method(#searchAll, [query]),
                  ),
                ),
          )
          as _i5.Future<_i2.SearchAllResultEntity>);

  @override
  _i5.Future<List<_i6.TrackResultEntity>> searchTracks(
    String? query, {
    int? page = 1,
    int? limit = 20,
    _i7.TrackSearchFilters? filters = const _i7.TrackSearchFilters(),
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #searchTracks,
              [query],
              {#page: page, #limit: limit, #filters: filters},
            ),
            returnValue: _i5.Future<List<_i6.TrackResultEntity>>.value(
              <_i6.TrackResultEntity>[],
            ),
            returnValueForMissingStub:
                _i5.Future<List<_i6.TrackResultEntity>>.value(
                  <_i6.TrackResultEntity>[],
                ),
          )
          as _i5.Future<List<_i6.TrackResultEntity>>);

  @override
  _i5.Future<List<_i8.ProfileResultEntity>> searchProfiles(
    String? query, {
    int? page = 1,
    int? limit = 20,
    _i7.PeopleSearchFilters? filters = const _i7.PeopleSearchFilters(),
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #searchProfiles,
              [query],
              {#page: page, #limit: limit, #filters: filters},
            ),
            returnValue: _i5.Future<List<_i8.ProfileResultEntity>>.value(
              <_i8.ProfileResultEntity>[],
            ),
            returnValueForMissingStub:
                _i5.Future<List<_i8.ProfileResultEntity>>.value(
                  <_i8.ProfileResultEntity>[],
                ),
          )
          as _i5.Future<List<_i8.ProfileResultEntity>>);

  @override
  _i5.Future<List<_i9.PlaylistResultEntity>> searchPlaylists(
    String? query, {
    int? page = 1,
    int? limit = 20,
    _i7.CollectionSearchFilters? filters = const _i7.CollectionSearchFilters(),
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #searchPlaylists,
              [query],
              {#page: page, #limit: limit, #filters: filters},
            ),
            returnValue: _i5.Future<List<_i9.PlaylistResultEntity>>.value(
              <_i9.PlaylistResultEntity>[],
            ),
            returnValueForMissingStub:
                _i5.Future<List<_i9.PlaylistResultEntity>>.value(
                  <_i9.PlaylistResultEntity>[],
                ),
          )
          as _i5.Future<List<_i9.PlaylistResultEntity>>);

  @override
  _i5.Future<List<_i10.AlbumResultEntity>> searchAlbums(
    String? query, {
    int? page = 1,
    int? limit = 20,
    _i7.CollectionSearchFilters? filters = const _i7.CollectionSearchFilters(),
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #searchAlbums,
              [query],
              {#page: page, #limit: limit, #filters: filters},
            ),
            returnValue: _i5.Future<List<_i10.AlbumResultEntity>>.value(
              <_i10.AlbumResultEntity>[],
            ),
            returnValueForMissingStub:
                _i5.Future<List<_i10.AlbumResultEntity>>.value(
                  <_i10.AlbumResultEntity>[],
                ),
          )
          as _i5.Future<List<_i10.AlbumResultEntity>>);

  @override
  _i5.Future<List<_i11.SearchGenreEntity>> getGenres() =>
      (super.noSuchMethod(
            Invocation.method(#getGenres, []),
            returnValue: _i5.Future<List<_i11.SearchGenreEntity>>.value(
              <_i11.SearchGenreEntity>[],
            ),
            returnValueForMissingStub:
                _i5.Future<List<_i11.SearchGenreEntity>>.value(
                  <_i11.SearchGenreEntity>[],
                ),
          )
          as _i5.Future<List<_i11.SearchGenreEntity>>);

  @override
  _i5.Future<_i3.GenreDetailEntity> getGenreDetail(String? genreId) =>
      (super.noSuchMethod(
            Invocation.method(#getGenreDetail, [genreId]),
            returnValue: _i5.Future<_i3.GenreDetailEntity>.value(
              _FakeGenreDetailEntity_1(
                this,
                Invocation.method(#getGenreDetail, [genreId]),
              ),
            ),
            returnValueForMissingStub: _i5.Future<_i3.GenreDetailEntity>.value(
              _FakeGenreDetailEntity_1(
                this,
                Invocation.method(#getGenreDetail, [genreId]),
              ),
            ),
          )
          as _i5.Future<_i3.GenreDetailEntity>);
}
